"""
    VIER Cognitive Voice Dialog API

    CVG dialog history  # noqa: E501

    The version of the OpenAPI document: 1.24.4
    Contact: support@vier.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cvg_sdk
from cvg_sdk.model.prompt_type import PromptType
globals()['PromptType'] = PromptType
from cvg_sdk.model.prompt_all_of import PromptAllOf


class TestPromptAllOf(unittest.TestCase):
    """PromptAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPromptAllOf(self):
        """Test PromptAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PromptAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
