"""
    VIER Cognitive Voice Recording API

    With the Recording API, client applications can manage recordings that have previously been created using the Call or Assist APIs.  # noqa: E501

    The version of the OpenAPI document: 1.24.4
    Contact: support@vier.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cvg_sdk
from cvg_sdk.model.text_all_of import TextAllOf


class TestTextAllOf(unittest.TestCase):
    """TextAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextAllOf(self):
        """Test TextAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
