"""
    VIER Cognitive Voice Dialog API

    CVG dialog history  # noqa: E501

    The version of the OpenAPI document: 1.24.4
    Contact: support@vier.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cvg_sdk
from cvg_sdk.model.confidence import Confidence
from cvg_sdk.model.language import Language
globals()['Confidence'] = Confidence
globals()['Language'] = Language
from cvg_sdk.model.transcription_all_of import TranscriptionAllOf


class TestTranscriptionAllOf(unittest.TestCase):
    """TranscriptionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscriptionAllOf(self):
        """Test TranscriptionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TranscriptionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
