# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.well_test_pres_travs_api import WellTestPresTravsApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestWellTestPresTravsApi(unittest.TestCase):
    """WellTestPresTravsApi unit test stubs"""

    def setUp(self):
        self.api = WellTestPresTravsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_well_test_pres_trav(self):
        """Test case for get_well_test_pres_trav

        Get entity from WellTestPresTravs by key  # noqa: E501
        """
        pass

    def test_list_well_test_pres_trav(self):
        """Test case for list_well_test_pres_trav

        Get entities from WellTestPresTravs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
