# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.loc_offshores_api import LocOffshoresApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestLocOffshoresApi(unittest.TestCase):
    """LocOffshoresApi unit test stubs"""

    def setUp(self):
        self.api = LocOffshoresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_loc_offshore(self):
        """Test case for get_loc_offshore

        Get entity from LocOffshores by key  # noqa: E501
        """
        pass

    def test_list_loc_offshore(self):
        """Test case for list_loc_offshore

        Get entities from LocOffshores  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
