# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.agreement_dates_api import AgreementDatesApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestAgreementDatesApi(unittest.TestCase):
    """AgreementDatesApi unit test stubs"""

    def setUp(self):
        self.api = AgreementDatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_agreement_date(self):
        """Test case for get_agreement_date

        Get entity from AgreementDates by key  # noqa: E501
        """
        pass

    def test_list_agreement_date(self):
        """Test case for list_agreement_date

        Get entities from AgreementDates  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
