# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.job_report_personnel_counts_api import JobReportPersonnelCountsApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestJobReportPersonnelCountsApi(unittest.TestCase):
    """JobReportPersonnelCountsApi unit test stubs"""

    def setUp(self):
        self.api = JobReportPersonnelCountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job_report_personnel_count(self):
        """Test case for get_job_report_personnel_count

        Get entity from JobReportPersonnelCounts by key  # noqa: E501
        """
        pass

    def test_list_job_report_personnel_count(self):
        """Test case for list_job_report_personnel_count

        Get entities from JobReportPersonnelCounts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
