"""RubberDoc Package  

This package contains all of the code which generated these reference docs!  

This markdown here was generated by the \__init__.py file for this package. 
I have a configuration set to rename \__init__.py files to 'about'. 
You could set aliases for your filenames in the config file as you see fit for your generations!

Happy Documenting!
"""
__version__ = '0.1.0'
