# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.models.one_of_loc_congressional_range import OneOfLocCongressionalRange  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestOneOfLocCongressionalRange(unittest.TestCase):
    """OneOfLocCongressionalRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfLocCongressionalRange(self):
        """Test OneOfLocCongressionalRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wellview_odata_api.models.one_of_loc_congressional_range.OneOfLocCongressionalRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
