# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.loc_lat_long_utms_api import LocLatLongUtmsApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestLocLatLongUtmsApi(unittest.TestCase):
    """LocLatLongUtmsApi unit test stubs"""

    def setUp(self):
        self.api = LocLatLongUtmsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_loc_lat_long_utm(self):
        """Test case for get_loc_lat_long_utm

        Get entity from LocLatLongUtms by key  # noqa: E501
        """
        pass

    def test_list_loc_lat_long_utm(self):
        """Test case for list_loc_lat_long_utm

        Get entities from LocLatLongUtms  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
