# coding: utf-8

"""
    Camunda Platform REST API

    OpenApi Spec for Camunda Platform REST API.  # noqa: E501

    The version of the OpenAPI document: 7.17.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import generic_camunda_client
from generic_camunda_client.api.authorization_api import AuthorizationApi  # noqa: E501
from generic_camunda_client.rest import ApiException


class TestAuthorizationApi(unittest.TestCase):
    """AuthorizationApi unit test stubs"""

    def setUp(self):
        self.api = generic_camunda_client.api.authorization_api.AuthorizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_available_operations_authorization(self):
        """Test case for available_operations_authorization

        Authorization Resource Options  # noqa: E501
        """
        pass

    def test_available_operations_authorization_instance(self):
        """Test case for available_operations_authorization_instance

        Authorization Resource Options  # noqa: E501
        """
        pass

    def test_create_authorization(self):
        """Test case for create_authorization

        Create a New Authorization  # noqa: E501
        """
        pass

    def test_delete_authorization(self):
        """Test case for delete_authorization

        Delete Authorization  # noqa: E501
        """
        pass

    def test_get_authorization(self):
        """Test case for get_authorization

        Get Authorization  # noqa: E501
        """
        pass

    def test_get_authorization_count(self):
        """Test case for get_authorization_count

        Get Authorization Count  # noqa: E501
        """
        pass

    def test_is_user_authorized(self):
        """Test case for is_user_authorized

        Perform an Authorization Check  # noqa: E501
        """
        pass

    def test_query_authorizations(self):
        """Test case for query_authorizations

        Get Authorizations  # noqa: E501
        """
        pass

    def test_update_authorization(self):
        """Test case for update_authorization

        Update an Authorization  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
