# coding: utf-8

"""
    Camunda Platform REST API

    OpenApi Spec for Camunda Platform REST API.  # noqa: E501

    The version of the OpenAPI document: 7.17.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import generic_camunda_client
from generic_camunda_client.api.historic_decision_instance_api import HistoricDecisionInstanceApi  # noqa: E501
from generic_camunda_client.rest import ApiException


class TestHistoricDecisionInstanceApi(unittest.TestCase):
    """HistoricDecisionInstanceApi unit test stubs"""

    def setUp(self):
        self.api = generic_camunda_client.api.historic_decision_instance_api.HistoricDecisionInstanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_async(self):
        """Test case for delete_async

        Delete Async (POST)  # noqa: E501
        """
        pass

    def test_get_historic_decision_instance(self):
        """Test case for get_historic_decision_instance

        Get Historic Decision Instance  # noqa: E501
        """
        pass

    def test_get_historic_decision_instances(self):
        """Test case for get_historic_decision_instances

        Get Historic Decision Instances  # noqa: E501
        """
        pass

    def test_get_historic_decision_instances_count(self):
        """Test case for get_historic_decision_instances_count

        Get Historic Decision Instance Count  # noqa: E501
        """
        pass

    def test_set_removal_time_async_historic_decision_instance(self):
        """Test case for set_removal_time_async_historic_decision_instance

        Set Removal Time Async (POST)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
