# coding: utf-8

"""
    Camunda Platform REST API

    OpenApi Spec for Camunda Platform REST API.  # noqa: E501

    The version of the OpenAPI document: 7.17.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import generic_camunda_client
from generic_camunda_client.api.historic_detail_api import HistoricDetailApi  # noqa: E501
from generic_camunda_client.rest import ApiException


class TestHistoricDetailApi(unittest.TestCase):
    """HistoricDetailApi unit test stubs"""

    def setUp(self):
        self.api = generic_camunda_client.api.historic_detail_api.HistoricDetailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_historic_details(self):
        """Test case for get_historic_details

        Get Historic Details  # noqa: E501
        """
        pass

    def test_get_historic_details_count(self):
        """Test case for get_historic_details_count

        Get Historic Detail Count  # noqa: E501
        """
        pass

    def test_historic_detail(self):
        """Test case for historic_detail

        Get Historic Detail  # noqa: E501
        """
        pass

    def test_historic_detail_binary(self):
        """Test case for historic_detail_binary

        Get Historic Detail (Binary)  # noqa: E501
        """
        pass

    def test_query_historic_details(self):
        """Test case for query_historic_details

        Get Historic Details (POST)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
