
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-25T06:50:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "515ee356976b39df0511e97b681f8091d3dba77f",
 "version": "1.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
