# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from wellview_sdk_api import schemas  # noqa: F401


class FormationData(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "idrec",
            "idwell",
        }
        
        class properties:
            idrec = schemas.StrSchema
            idwell = schemas.StrSchema
            collapsepres = schemas.NumberSchema
            com = schemas.StrSchema
            depthdrillingbtm = schemas.NumberSchema
            depthdrillingsource = schemas.StrSchema
            depthdrillingtop = schemas.NumberSchema
            depthfinalbtm = schemas.NumberSchema
            depthfinalsource = schemas.StrSchema
            depthfinaltop = schemas.NumberSchema
            depthgasoil = schemas.NumberSchema
            depthgaswater = schemas.NumberSchema
            depthmdprogbtm = schemas.NumberSchema
            depthmdprogtop = schemas.NumberSchema
            depthoilwater = schemas.NumberSchema
            depthssprogbtm = schemas.NumberSchema
            depthssprogtop = schemas.NumberSchema
            deschro = schemas.StrSchema
            desfluid = schemas.StrSchema
            deslithology = schemas.StrSchema
            dipangle = schemas.NumberSchema
            dipazimuth = schemas.NumberSchema
            drillingconsid = schemas.StrSchema
            elementtyp = schemas.StrSchema
            formationida = schemas.StrSchema
            formationidb = schemas.StrSchema
            formationidc = schemas.StrSchema
            formcode = schemas.StrSchema
            formname = schemas.StrSchema
            fracpres = schemas.NumberSchema
            geologicage = schemas.StrSchema
            grosspay = schemas.NumberSchema
            h2sconc = schemas.NumberSchema
            iconname = schemas.StrSchema
            idrecparent = schemas.StrSchema
            integrityconsid = schemas.StrSchema
            kh90 = schemas.NumberSchema
            kmax = schemas.NumberSchema
            kv = schemas.NumberSchema
            layername = schemas.StrSchema
            mudconsid = schemas.StrSchema
            netpay = schemas.NumberSchema
            noteothergas = schemas.StrSchema
            porepres = schemas.NumberSchema
            porosity = schemas.NumberSchema
            ropinterpreted = schemas.NumberSchema
            stress = schemas.NumberSchema
            temp = schemas.NumberSchema
            usernum1 = schemas.NumberSchema
            usernum2 = schemas.NumberSchema
            usernum3 = schemas.NumberSchema
            watersat = schemas.NumberSchema
            weightbitumen = schemas.NumberSchema
            __annotations__ = {
                "idrec": idrec,
                "idwell": idwell,
                "collapsepres": collapsepres,
                "com": com,
                "depthdrillingbtm": depthdrillingbtm,
                "depthdrillingsource": depthdrillingsource,
                "depthdrillingtop": depthdrillingtop,
                "depthfinalbtm": depthfinalbtm,
                "depthfinalsource": depthfinalsource,
                "depthfinaltop": depthfinaltop,
                "depthgasoil": depthgasoil,
                "depthgaswater": depthgaswater,
                "depthmdprogbtm": depthmdprogbtm,
                "depthmdprogtop": depthmdprogtop,
                "depthoilwater": depthoilwater,
                "depthssprogbtm": depthssprogbtm,
                "depthssprogtop": depthssprogtop,
                "deschro": deschro,
                "desfluid": desfluid,
                "deslithology": deslithology,
                "dipangle": dipangle,
                "dipazimuth": dipazimuth,
                "drillingconsid": drillingconsid,
                "elementtyp": elementtyp,
                "formationida": formationida,
                "formationidb": formationidb,
                "formationidc": formationidc,
                "formcode": formcode,
                "formname": formname,
                "fracpres": fracpres,
                "geologicage": geologicage,
                "grosspay": grosspay,
                "h2sconc": h2sconc,
                "iconname": iconname,
                "idrecparent": idrecparent,
                "integrityconsid": integrityconsid,
                "kh90": kh90,
                "kmax": kmax,
                "kv": kv,
                "layername": layername,
                "mudconsid": mudconsid,
                "netpay": netpay,
                "noteothergas": noteothergas,
                "porepres": porepres,
                "porosity": porosity,
                "ropinterpreted": ropinterpreted,
                "stress": stress,
                "temp": temp,
                "usernum1": usernum1,
                "usernum2": usernum2,
                "usernum3": usernum3,
                "watersat": watersat,
                "weightbitumen": weightbitumen,
            }
    
    idrec: MetaOapg.properties.idrec
    idwell: MetaOapg.properties.idwell
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["idrec"]) -> MetaOapg.properties.idrec: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["idwell"]) -> MetaOapg.properties.idwell: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["collapsepres"]) -> MetaOapg.properties.collapsepres: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["com"]) -> MetaOapg.properties.com: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthdrillingbtm"]) -> MetaOapg.properties.depthdrillingbtm: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthdrillingsource"]) -> MetaOapg.properties.depthdrillingsource: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthdrillingtop"]) -> MetaOapg.properties.depthdrillingtop: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthfinalbtm"]) -> MetaOapg.properties.depthfinalbtm: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthfinalsource"]) -> MetaOapg.properties.depthfinalsource: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthfinaltop"]) -> MetaOapg.properties.depthfinaltop: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthgasoil"]) -> MetaOapg.properties.depthgasoil: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthgaswater"]) -> MetaOapg.properties.depthgaswater: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthmdprogbtm"]) -> MetaOapg.properties.depthmdprogbtm: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthmdprogtop"]) -> MetaOapg.properties.depthmdprogtop: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthoilwater"]) -> MetaOapg.properties.depthoilwater: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthssprogbtm"]) -> MetaOapg.properties.depthssprogbtm: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["depthssprogtop"]) -> MetaOapg.properties.depthssprogtop: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deschro"]) -> MetaOapg.properties.deschro: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["desfluid"]) -> MetaOapg.properties.desfluid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deslithology"]) -> MetaOapg.properties.deslithology: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dipangle"]) -> MetaOapg.properties.dipangle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dipazimuth"]) -> MetaOapg.properties.dipazimuth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["drillingconsid"]) -> MetaOapg.properties.drillingconsid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["elementtyp"]) -> MetaOapg.properties.elementtyp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["formationida"]) -> MetaOapg.properties.formationida: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["formationidb"]) -> MetaOapg.properties.formationidb: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["formationidc"]) -> MetaOapg.properties.formationidc: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["formcode"]) -> MetaOapg.properties.formcode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["formname"]) -> MetaOapg.properties.formname: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fracpres"]) -> MetaOapg.properties.fracpres: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["geologicage"]) -> MetaOapg.properties.geologicage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["grosspay"]) -> MetaOapg.properties.grosspay: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["h2sconc"]) -> MetaOapg.properties.h2sconc: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iconname"]) -> MetaOapg.properties.iconname: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["idrecparent"]) -> MetaOapg.properties.idrecparent: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["integrityconsid"]) -> MetaOapg.properties.integrityconsid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kh90"]) -> MetaOapg.properties.kh90: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kmax"]) -> MetaOapg.properties.kmax: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kv"]) -> MetaOapg.properties.kv: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["layername"]) -> MetaOapg.properties.layername: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mudconsid"]) -> MetaOapg.properties.mudconsid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["netpay"]) -> MetaOapg.properties.netpay: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["noteothergas"]) -> MetaOapg.properties.noteothergas: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["porepres"]) -> MetaOapg.properties.porepres: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["porosity"]) -> MetaOapg.properties.porosity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ropinterpreted"]) -> MetaOapg.properties.ropinterpreted: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stress"]) -> MetaOapg.properties.stress: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["temp"]) -> MetaOapg.properties.temp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["usernum1"]) -> MetaOapg.properties.usernum1: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["usernum2"]) -> MetaOapg.properties.usernum2: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["usernum3"]) -> MetaOapg.properties.usernum3: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["watersat"]) -> MetaOapg.properties.watersat: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["weightbitumen"]) -> MetaOapg.properties.weightbitumen: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["idrec", "idwell", "collapsepres", "com", "depthdrillingbtm", "depthdrillingsource", "depthdrillingtop", "depthfinalbtm", "depthfinalsource", "depthfinaltop", "depthgasoil", "depthgaswater", "depthmdprogbtm", "depthmdprogtop", "depthoilwater", "depthssprogbtm", "depthssprogtop", "deschro", "desfluid", "deslithology", "dipangle", "dipazimuth", "drillingconsid", "elementtyp", "formationida", "formationidb", "formationidc", "formcode", "formname", "fracpres", "geologicage", "grosspay", "h2sconc", "iconname", "idrecparent", "integrityconsid", "kh90", "kmax", "kv", "layername", "mudconsid", "netpay", "noteothergas", "porepres", "porosity", "ropinterpreted", "stress", "temp", "usernum1", "usernum2", "usernum3", "watersat", "weightbitumen", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["idrec"]) -> MetaOapg.properties.idrec: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["idwell"]) -> MetaOapg.properties.idwell: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["collapsepres"]) -> typing.Union[MetaOapg.properties.collapsepres, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["com"]) -> typing.Union[MetaOapg.properties.com, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthdrillingbtm"]) -> typing.Union[MetaOapg.properties.depthdrillingbtm, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthdrillingsource"]) -> typing.Union[MetaOapg.properties.depthdrillingsource, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthdrillingtop"]) -> typing.Union[MetaOapg.properties.depthdrillingtop, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthfinalbtm"]) -> typing.Union[MetaOapg.properties.depthfinalbtm, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthfinalsource"]) -> typing.Union[MetaOapg.properties.depthfinalsource, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthfinaltop"]) -> typing.Union[MetaOapg.properties.depthfinaltop, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthgasoil"]) -> typing.Union[MetaOapg.properties.depthgasoil, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthgaswater"]) -> typing.Union[MetaOapg.properties.depthgaswater, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthmdprogbtm"]) -> typing.Union[MetaOapg.properties.depthmdprogbtm, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthmdprogtop"]) -> typing.Union[MetaOapg.properties.depthmdprogtop, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthoilwater"]) -> typing.Union[MetaOapg.properties.depthoilwater, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthssprogbtm"]) -> typing.Union[MetaOapg.properties.depthssprogbtm, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["depthssprogtop"]) -> typing.Union[MetaOapg.properties.depthssprogtop, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deschro"]) -> typing.Union[MetaOapg.properties.deschro, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["desfluid"]) -> typing.Union[MetaOapg.properties.desfluid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deslithology"]) -> typing.Union[MetaOapg.properties.deslithology, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dipangle"]) -> typing.Union[MetaOapg.properties.dipangle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dipazimuth"]) -> typing.Union[MetaOapg.properties.dipazimuth, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["drillingconsid"]) -> typing.Union[MetaOapg.properties.drillingconsid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["elementtyp"]) -> typing.Union[MetaOapg.properties.elementtyp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["formationida"]) -> typing.Union[MetaOapg.properties.formationida, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["formationidb"]) -> typing.Union[MetaOapg.properties.formationidb, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["formationidc"]) -> typing.Union[MetaOapg.properties.formationidc, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["formcode"]) -> typing.Union[MetaOapg.properties.formcode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["formname"]) -> typing.Union[MetaOapg.properties.formname, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fracpres"]) -> typing.Union[MetaOapg.properties.fracpres, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["geologicage"]) -> typing.Union[MetaOapg.properties.geologicage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["grosspay"]) -> typing.Union[MetaOapg.properties.grosspay, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["h2sconc"]) -> typing.Union[MetaOapg.properties.h2sconc, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iconname"]) -> typing.Union[MetaOapg.properties.iconname, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["idrecparent"]) -> typing.Union[MetaOapg.properties.idrecparent, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["integrityconsid"]) -> typing.Union[MetaOapg.properties.integrityconsid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kh90"]) -> typing.Union[MetaOapg.properties.kh90, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kmax"]) -> typing.Union[MetaOapg.properties.kmax, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kv"]) -> typing.Union[MetaOapg.properties.kv, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["layername"]) -> typing.Union[MetaOapg.properties.layername, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mudconsid"]) -> typing.Union[MetaOapg.properties.mudconsid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["netpay"]) -> typing.Union[MetaOapg.properties.netpay, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["noteothergas"]) -> typing.Union[MetaOapg.properties.noteothergas, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["porepres"]) -> typing.Union[MetaOapg.properties.porepres, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["porosity"]) -> typing.Union[MetaOapg.properties.porosity, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ropinterpreted"]) -> typing.Union[MetaOapg.properties.ropinterpreted, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stress"]) -> typing.Union[MetaOapg.properties.stress, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["temp"]) -> typing.Union[MetaOapg.properties.temp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["usernum1"]) -> typing.Union[MetaOapg.properties.usernum1, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["usernum2"]) -> typing.Union[MetaOapg.properties.usernum2, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["usernum3"]) -> typing.Union[MetaOapg.properties.usernum3, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["watersat"]) -> typing.Union[MetaOapg.properties.watersat, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["weightbitumen"]) -> typing.Union[MetaOapg.properties.weightbitumen, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["idrec", "idwell", "collapsepres", "com", "depthdrillingbtm", "depthdrillingsource", "depthdrillingtop", "depthfinalbtm", "depthfinalsource", "depthfinaltop", "depthgasoil", "depthgaswater", "depthmdprogbtm", "depthmdprogtop", "depthoilwater", "depthssprogbtm", "depthssprogtop", "deschro", "desfluid", "deslithology", "dipangle", "dipazimuth", "drillingconsid", "elementtyp", "formationida", "formationidb", "formationidc", "formcode", "formname", "fracpres", "geologicage", "grosspay", "h2sconc", "iconname", "idrecparent", "integrityconsid", "kh90", "kmax", "kv", "layername", "mudconsid", "netpay", "noteothergas", "porepres", "porosity", "ropinterpreted", "stress", "temp", "usernum1", "usernum2", "usernum3", "watersat", "weightbitumen", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        idrec: typing.Union[MetaOapg.properties.idrec, str, ],
        idwell: typing.Union[MetaOapg.properties.idwell, str, ],
        collapsepres: typing.Union[MetaOapg.properties.collapsepres, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        com: typing.Union[MetaOapg.properties.com, str, schemas.Unset] = schemas.unset,
        depthdrillingbtm: typing.Union[MetaOapg.properties.depthdrillingbtm, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthdrillingsource: typing.Union[MetaOapg.properties.depthdrillingsource, str, schemas.Unset] = schemas.unset,
        depthdrillingtop: typing.Union[MetaOapg.properties.depthdrillingtop, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthfinalbtm: typing.Union[MetaOapg.properties.depthfinalbtm, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthfinalsource: typing.Union[MetaOapg.properties.depthfinalsource, str, schemas.Unset] = schemas.unset,
        depthfinaltop: typing.Union[MetaOapg.properties.depthfinaltop, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthgasoil: typing.Union[MetaOapg.properties.depthgasoil, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthgaswater: typing.Union[MetaOapg.properties.depthgaswater, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthmdprogbtm: typing.Union[MetaOapg.properties.depthmdprogbtm, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthmdprogtop: typing.Union[MetaOapg.properties.depthmdprogtop, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthoilwater: typing.Union[MetaOapg.properties.depthoilwater, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthssprogbtm: typing.Union[MetaOapg.properties.depthssprogbtm, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        depthssprogtop: typing.Union[MetaOapg.properties.depthssprogtop, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        deschro: typing.Union[MetaOapg.properties.deschro, str, schemas.Unset] = schemas.unset,
        desfluid: typing.Union[MetaOapg.properties.desfluid, str, schemas.Unset] = schemas.unset,
        deslithology: typing.Union[MetaOapg.properties.deslithology, str, schemas.Unset] = schemas.unset,
        dipangle: typing.Union[MetaOapg.properties.dipangle, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        dipazimuth: typing.Union[MetaOapg.properties.dipazimuth, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        drillingconsid: typing.Union[MetaOapg.properties.drillingconsid, str, schemas.Unset] = schemas.unset,
        elementtyp: typing.Union[MetaOapg.properties.elementtyp, str, schemas.Unset] = schemas.unset,
        formationida: typing.Union[MetaOapg.properties.formationida, str, schemas.Unset] = schemas.unset,
        formationidb: typing.Union[MetaOapg.properties.formationidb, str, schemas.Unset] = schemas.unset,
        formationidc: typing.Union[MetaOapg.properties.formationidc, str, schemas.Unset] = schemas.unset,
        formcode: typing.Union[MetaOapg.properties.formcode, str, schemas.Unset] = schemas.unset,
        formname: typing.Union[MetaOapg.properties.formname, str, schemas.Unset] = schemas.unset,
        fracpres: typing.Union[MetaOapg.properties.fracpres, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        geologicage: typing.Union[MetaOapg.properties.geologicage, str, schemas.Unset] = schemas.unset,
        grosspay: typing.Union[MetaOapg.properties.grosspay, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        h2sconc: typing.Union[MetaOapg.properties.h2sconc, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        iconname: typing.Union[MetaOapg.properties.iconname, str, schemas.Unset] = schemas.unset,
        idrecparent: typing.Union[MetaOapg.properties.idrecparent, str, schemas.Unset] = schemas.unset,
        integrityconsid: typing.Union[MetaOapg.properties.integrityconsid, str, schemas.Unset] = schemas.unset,
        kh90: typing.Union[MetaOapg.properties.kh90, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        kmax: typing.Union[MetaOapg.properties.kmax, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        kv: typing.Union[MetaOapg.properties.kv, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        layername: typing.Union[MetaOapg.properties.layername, str, schemas.Unset] = schemas.unset,
        mudconsid: typing.Union[MetaOapg.properties.mudconsid, str, schemas.Unset] = schemas.unset,
        netpay: typing.Union[MetaOapg.properties.netpay, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        noteothergas: typing.Union[MetaOapg.properties.noteothergas, str, schemas.Unset] = schemas.unset,
        porepres: typing.Union[MetaOapg.properties.porepres, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        porosity: typing.Union[MetaOapg.properties.porosity, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        ropinterpreted: typing.Union[MetaOapg.properties.ropinterpreted, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        stress: typing.Union[MetaOapg.properties.stress, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        temp: typing.Union[MetaOapg.properties.temp, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        usernum1: typing.Union[MetaOapg.properties.usernum1, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        usernum2: typing.Union[MetaOapg.properties.usernum2, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        usernum3: typing.Union[MetaOapg.properties.usernum3, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        watersat: typing.Union[MetaOapg.properties.watersat, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        weightbitumen: typing.Union[MetaOapg.properties.weightbitumen, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FormationData':
        return super().__new__(
            cls,
            *args,
            idrec=idrec,
            idwell=idwell,
            collapsepres=collapsepres,
            com=com,
            depthdrillingbtm=depthdrillingbtm,
            depthdrillingsource=depthdrillingsource,
            depthdrillingtop=depthdrillingtop,
            depthfinalbtm=depthfinalbtm,
            depthfinalsource=depthfinalsource,
            depthfinaltop=depthfinaltop,
            depthgasoil=depthgasoil,
            depthgaswater=depthgaswater,
            depthmdprogbtm=depthmdprogbtm,
            depthmdprogtop=depthmdprogtop,
            depthoilwater=depthoilwater,
            depthssprogbtm=depthssprogbtm,
            depthssprogtop=depthssprogtop,
            deschro=deschro,
            desfluid=desfluid,
            deslithology=deslithology,
            dipangle=dipangle,
            dipazimuth=dipazimuth,
            drillingconsid=drillingconsid,
            elementtyp=elementtyp,
            formationida=formationida,
            formationidb=formationidb,
            formationidc=formationidc,
            formcode=formcode,
            formname=formname,
            fracpres=fracpres,
            geologicage=geologicage,
            grosspay=grosspay,
            h2sconc=h2sconc,
            iconname=iconname,
            idrecparent=idrecparent,
            integrityconsid=integrityconsid,
            kh90=kh90,
            kmax=kmax,
            kv=kv,
            layername=layername,
            mudconsid=mudconsid,
            netpay=netpay,
            noteothergas=noteothergas,
            porepres=porepres,
            porosity=porosity,
            ropinterpreted=ropinterpreted,
            stress=stress,
            temp=temp,
            usernum1=usernum1,
            usernum2=usernum2,
            usernum3=usernum3,
            watersat=watersat,
            weightbitumen=weightbitumen,
            _configuration=_configuration,
            **kwargs,
        )
