# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.models.one_of_cas_tension import OneOfCasTension  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestOneOfCasTension(unittest.TestCase):
    """OneOfCasTension unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfCasTension(self):
        """Test OneOfCasTension"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wellview_odata_api.models.one_of_cas_tension.OneOfCasTension()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
