# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.riser_comps_api import RiserCompsApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestRiserCompsApi(unittest.TestCase):
    """RiserCompsApi unit test stubs"""

    def setUp(self):
        self.api = RiserCompsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_riser_comp(self):
        """Test case for get_riser_comp

        Get entity from RiserComps by key  # noqa: E501
        """
        pass

    def test_list_riser_comp(self):
        """Test case for list_riser_comp

        Get entities from RiserComps  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
