# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.other_inhole_statuses_api import OtherInholeStatusesApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestOtherInholeStatusesApi(unittest.TestCase):
    """OtherInholeStatusesApi unit test stubs"""

    def setUp(self):
        self.api = OtherInholeStatusesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_other_inhole_status(self):
        """Test case for get_other_inhole_status

        Get entity from OtherInholeStatuses by key  # noqa: E501
        """
        pass

    def test_list_other_inhole_status(self):
        """Test case for list_other_inhole_status

        Get entities from OtherInholeStatuses  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
