# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.rod_comp_polish_rods_api import RodCompPolishRodsApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestRodCompPolishRodsApi(unittest.TestCase):
    """RodCompPolishRodsApi unit test stubs"""

    def setUp(self):
        self.api = RodCompPolishRodsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_rod_comp_polish_rod(self):
        """Test case for get_rod_comp_polish_rod

        Get entity from RodCompPolishRods by key  # noqa: E501
        """
        pass

    def test_list_rod_comp_polish_rod(self):
        """Test case for list_rod_comp_polish_rod

        Get entities from RodCompPolishRods  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
