# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.job_report_mud_vols_api import JobReportMudVolsApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestJobReportMudVolsApi(unittest.TestCase):
    """JobReportMudVolsApi unit test stubs"""

    def setUp(self):
        self.api = JobReportMudVolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job_report_mud_vol(self):
        """Test case for get_job_report_mud_vol

        Get entity from JobReportMudVols by key  # noqa: E501
        """
        pass

    def test_list_job_report_mud_vol(self):
        """Test case for list_job_report_mud_vol

        Get entities from JobReportMudVols  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
