# coding: utf-8

"""
    BMLT

    BMLT Admin API Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import bmlt_client
from bmlt_client.model.not_found_error import NotFoundError
from bmlt_client import configuration


class TestNotFoundError(unittest.TestCase):
    """NotFoundError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
