
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-23T10:19:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9bf29872fd3698f5cf020609a46a03e2b435aaa",
 "version": "0.0.125"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
