# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CasCompEcp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cas_comp': 'AnyOfCasCompEcpCasComp',
        'ecpload': 'OneOfCasCompEcpEcpload',
        'equivholesz': 'OneOfCasCompEcpEquivholesz',
        'icvpresact': 'OneOfCasCompEcpIcvpresact',
        'icvpresset': 'OneOfCasCompEcpIcvpresset',
        'idrec': 'str',
        'idrecparent': 'str',
        'idwell': 'str',
        'inflationmeth': 'str',
        'inflfluidden': 'OneOfCasCompEcpInflfluidden',
        'inflfluidtyp': 'str',
        'inflvol': 'OneOfCasCompEcpInflvol',
        'knockoffrod': 'int',
        'reqrelease': 'str',
        'reqset': 'str',
        'sealload': 'OneOfCasCompEcpSealload',
        'selectiveinfl': 'int',
        'svpresact': 'OneOfCasCompEcpSvpresact',
        'svpresset': 'OneOfCasCompEcpSvpresset',
        'syscreatedate': 'datetime',
        'syscreateuser': 'str',
        'syslockchildren': 'int',
        'syslockchildrenui': 'int',
        'syslockdate': 'datetime',
        'syslockme': 'int',
        'syslockmeui': 'int',
        'sysmoddate': 'datetime',
        'sysmoduser': 'str',
        'systag': 'str',
        'typ': 'str'
    }

    attribute_map = {
        'cas_comp': 'casComp',
        'ecpload': 'ecpload',
        'equivholesz': 'equivholesz',
        'icvpresact': 'icvpresact',
        'icvpresset': 'icvpresset',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idwell': 'idwell',
        'inflationmeth': 'inflationmeth',
        'inflfluidden': 'inflfluidden',
        'inflfluidtyp': 'inflfluidtyp',
        'inflvol': 'inflvol',
        'knockoffrod': 'knockoffrod',
        'reqrelease': 'reqrelease',
        'reqset': 'reqset',
        'sealload': 'sealload',
        'selectiveinfl': 'selectiveinfl',
        'svpresact': 'svpresact',
        'svpresset': 'svpresset',
        'syscreatedate': 'syscreatedate',
        'syscreateuser': 'syscreateuser',
        'syslockchildren': 'syslockchildren',
        'syslockchildrenui': 'syslockchildrenui',
        'syslockdate': 'syslockdate',
        'syslockme': 'syslockme',
        'syslockmeui': 'syslockmeui',
        'sysmoddate': 'sysmoddate',
        'sysmoduser': 'sysmoduser',
        'systag': 'systag',
        'typ': 'typ'
    }

    def __init__(self, cas_comp=None, ecpload=None, equivholesz=None, icvpresact=None, icvpresset=None, idrec=None, idrecparent=None, idwell=None, inflationmeth=None, inflfluidden=None, inflfluidtyp=None, inflvol=None, knockoffrod=None, reqrelease=None, reqset=None, sealload=None, selectiveinfl=None, svpresact=None, svpresset=None, syscreatedate=None, syscreateuser=None, syslockchildren=None, syslockchildrenui=None, syslockdate=None, syslockme=None, syslockmeui=None, sysmoddate=None, sysmoduser=None, systag=None, typ=None):  # noqa: E501
        """CasCompEcp - a model defined in Swagger"""  # noqa: E501
        self._cas_comp = None
        self._ecpload = None
        self._equivholesz = None
        self._icvpresact = None
        self._icvpresset = None
        self._idrec = None
        self._idrecparent = None
        self._idwell = None
        self._inflationmeth = None
        self._inflfluidden = None
        self._inflfluidtyp = None
        self._inflvol = None
        self._knockoffrod = None
        self._reqrelease = None
        self._reqset = None
        self._sealload = None
        self._selectiveinfl = None
        self._svpresact = None
        self._svpresset = None
        self._syscreatedate = None
        self._syscreateuser = None
        self._syslockchildren = None
        self._syslockchildrenui = None
        self._syslockdate = None
        self._syslockme = None
        self._syslockmeui = None
        self._sysmoddate = None
        self._sysmoduser = None
        self._systag = None
        self._typ = None
        self.discriminator = None
        if cas_comp is not None:
            self.cas_comp = cas_comp
        if ecpload is not None:
            self.ecpload = ecpload
        if equivholesz is not None:
            self.equivholesz = equivholesz
        if icvpresact is not None:
            self.icvpresact = icvpresact
        if icvpresset is not None:
            self.icvpresset = icvpresset
        if idrec is not None:
            self.idrec = idrec
        if idrecparent is not None:
            self.idrecparent = idrecparent
        if idwell is not None:
            self.idwell = idwell
        if inflationmeth is not None:
            self.inflationmeth = inflationmeth
        if inflfluidden is not None:
            self.inflfluidden = inflfluidden
        if inflfluidtyp is not None:
            self.inflfluidtyp = inflfluidtyp
        if inflvol is not None:
            self.inflvol = inflvol
        if knockoffrod is not None:
            self.knockoffrod = knockoffrod
        if reqrelease is not None:
            self.reqrelease = reqrelease
        if reqset is not None:
            self.reqset = reqset
        if sealload is not None:
            self.sealload = sealload
        if selectiveinfl is not None:
            self.selectiveinfl = selectiveinfl
        if svpresact is not None:
            self.svpresact = svpresact
        if svpresset is not None:
            self.svpresset = svpresset
        if syscreatedate is not None:
            self.syscreatedate = syscreatedate
        if syscreateuser is not None:
            self.syscreateuser = syscreateuser
        if syslockchildren is not None:
            self.syslockchildren = syslockchildren
        if syslockchildrenui is not None:
            self.syslockchildrenui = syslockchildrenui
        if syslockdate is not None:
            self.syslockdate = syslockdate
        if syslockme is not None:
            self.syslockme = syslockme
        if syslockmeui is not None:
            self.syslockmeui = syslockmeui
        if sysmoddate is not None:
            self.sysmoddate = sysmoddate
        if sysmoduser is not None:
            self.sysmoduser = sysmoduser
        if systag is not None:
            self.systag = systag
        if typ is not None:
            self.typ = typ

    @property
    def cas_comp(self):
        """Gets the cas_comp of this CasCompEcp.  # noqa: E501


        :return: The cas_comp of this CasCompEcp.  # noqa: E501
        :rtype: AnyOfCasCompEcpCasComp
        """
        return self._cas_comp

    @cas_comp.setter
    def cas_comp(self, cas_comp):
        """Sets the cas_comp of this CasCompEcp.


        :param cas_comp: The cas_comp of this CasCompEcp.  # noqa: E501
        :type: AnyOfCasCompEcpCasComp
        """

        self._cas_comp = cas_comp

    @property
    def ecpload(self):
        """Gets the ecpload of this CasCompEcp.  # noqa: E501


        :return: The ecpload of this CasCompEcp.  # noqa: E501
        :rtype: OneOfCasCompEcpEcpload
        """
        return self._ecpload

    @ecpload.setter
    def ecpload(self, ecpload):
        """Sets the ecpload of this CasCompEcp.


        :param ecpload: The ecpload of this CasCompEcp.  # noqa: E501
        :type: OneOfCasCompEcpEcpload
        """

        self._ecpload = ecpload

    @property
    def equivholesz(self):
        """Gets the equivholesz of this CasCompEcp.  # noqa: E501


        :return: The equivholesz of this CasCompEcp.  # noqa: E501
        :rtype: OneOfCasCompEcpEquivholesz
        """
        return self._equivholesz

    @equivholesz.setter
    def equivholesz(self, equivholesz):
        """Sets the equivholesz of this CasCompEcp.


        :param equivholesz: The equivholesz of this CasCompEcp.  # noqa: E501
        :type: OneOfCasCompEcpEquivholesz
        """

        self._equivholesz = equivholesz

    @property
    def icvpresact(self):
        """Gets the icvpresact of this CasCompEcp.  # noqa: E501


        :return: The icvpresact of this CasCompEcp.  # noqa: E501
        :rtype: OneOfCasCompEcpIcvpresact
        """
        return self._icvpresact

    @icvpresact.setter
    def icvpresact(self, icvpresact):
        """Sets the icvpresact of this CasCompEcp.


        :param icvpresact: The icvpresact of this CasCompEcp.  # noqa: E501
        :type: OneOfCasCompEcpIcvpresact
        """

        self._icvpresact = icvpresact

    @property
    def icvpresset(self):
        """Gets the icvpresset of this CasCompEcp.  # noqa: E501


        :return: The icvpresset of this CasCompEcp.  # noqa: E501
        :rtype: OneOfCasCompEcpIcvpresset
        """
        return self._icvpresset

    @icvpresset.setter
    def icvpresset(self, icvpresset):
        """Sets the icvpresset of this CasCompEcp.


        :param icvpresset: The icvpresset of this CasCompEcp.  # noqa: E501
        :type: OneOfCasCompEcpIcvpresset
        """

        self._icvpresset = icvpresset

    @property
    def idrec(self):
        """Gets the idrec of this CasCompEcp.  # noqa: E501


        :return: The idrec of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this CasCompEcp.


        :param idrec: The idrec of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this CasCompEcp.  # noqa: E501


        :return: The idrecparent of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this CasCompEcp.


        :param idrecparent: The idrecparent of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._idrecparent = idrecparent

    @property
    def idwell(self):
        """Gets the idwell of this CasCompEcp.  # noqa: E501


        :return: The idwell of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this CasCompEcp.


        :param idwell: The idwell of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._idwell = idwell

    @property
    def inflationmeth(self):
        """Gets the inflationmeth of this CasCompEcp.  # noqa: E501


        :return: The inflationmeth of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._inflationmeth

    @inflationmeth.setter
    def inflationmeth(self, inflationmeth):
        """Sets the inflationmeth of this CasCompEcp.


        :param inflationmeth: The inflationmeth of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._inflationmeth = inflationmeth

    @property
    def inflfluidden(self):
        """Gets the inflfluidden of this CasCompEcp.  # noqa: E501


        :return: The inflfluidden of this CasCompEcp.  # noqa: E501
        :rtype: OneOfCasCompEcpInflfluidden
        """
        return self._inflfluidden

    @inflfluidden.setter
    def inflfluidden(self, inflfluidden):
        """Sets the inflfluidden of this CasCompEcp.


        :param inflfluidden: The inflfluidden of this CasCompEcp.  # noqa: E501
        :type: OneOfCasCompEcpInflfluidden
        """

        self._inflfluidden = inflfluidden

    @property
    def inflfluidtyp(self):
        """Gets the inflfluidtyp of this CasCompEcp.  # noqa: E501


        :return: The inflfluidtyp of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._inflfluidtyp

    @inflfluidtyp.setter
    def inflfluidtyp(self, inflfluidtyp):
        """Sets the inflfluidtyp of this CasCompEcp.


        :param inflfluidtyp: The inflfluidtyp of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._inflfluidtyp = inflfluidtyp

    @property
    def inflvol(self):
        """Gets the inflvol of this CasCompEcp.  # noqa: E501


        :return: The inflvol of this CasCompEcp.  # noqa: E501
        :rtype: OneOfCasCompEcpInflvol
        """
        return self._inflvol

    @inflvol.setter
    def inflvol(self, inflvol):
        """Sets the inflvol of this CasCompEcp.


        :param inflvol: The inflvol of this CasCompEcp.  # noqa: E501
        :type: OneOfCasCompEcpInflvol
        """

        self._inflvol = inflvol

    @property
    def knockoffrod(self):
        """Gets the knockoffrod of this CasCompEcp.  # noqa: E501


        :return: The knockoffrod of this CasCompEcp.  # noqa: E501
        :rtype: int
        """
        return self._knockoffrod

    @knockoffrod.setter
    def knockoffrod(self, knockoffrod):
        """Sets the knockoffrod of this CasCompEcp.


        :param knockoffrod: The knockoffrod of this CasCompEcp.  # noqa: E501
        :type: int
        """

        self._knockoffrod = knockoffrod

    @property
    def reqrelease(self):
        """Gets the reqrelease of this CasCompEcp.  # noqa: E501


        :return: The reqrelease of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._reqrelease

    @reqrelease.setter
    def reqrelease(self, reqrelease):
        """Sets the reqrelease of this CasCompEcp.


        :param reqrelease: The reqrelease of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._reqrelease = reqrelease

    @property
    def reqset(self):
        """Gets the reqset of this CasCompEcp.  # noqa: E501


        :return: The reqset of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._reqset

    @reqset.setter
    def reqset(self, reqset):
        """Sets the reqset of this CasCompEcp.


        :param reqset: The reqset of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._reqset = reqset

    @property
    def sealload(self):
        """Gets the sealload of this CasCompEcp.  # noqa: E501


        :return: The sealload of this CasCompEcp.  # noqa: E501
        :rtype: OneOfCasCompEcpSealload
        """
        return self._sealload

    @sealload.setter
    def sealload(self, sealload):
        """Sets the sealload of this CasCompEcp.


        :param sealload: The sealload of this CasCompEcp.  # noqa: E501
        :type: OneOfCasCompEcpSealload
        """

        self._sealload = sealload

    @property
    def selectiveinfl(self):
        """Gets the selectiveinfl of this CasCompEcp.  # noqa: E501


        :return: The selectiveinfl of this CasCompEcp.  # noqa: E501
        :rtype: int
        """
        return self._selectiveinfl

    @selectiveinfl.setter
    def selectiveinfl(self, selectiveinfl):
        """Sets the selectiveinfl of this CasCompEcp.


        :param selectiveinfl: The selectiveinfl of this CasCompEcp.  # noqa: E501
        :type: int
        """

        self._selectiveinfl = selectiveinfl

    @property
    def svpresact(self):
        """Gets the svpresact of this CasCompEcp.  # noqa: E501


        :return: The svpresact of this CasCompEcp.  # noqa: E501
        :rtype: OneOfCasCompEcpSvpresact
        """
        return self._svpresact

    @svpresact.setter
    def svpresact(self, svpresact):
        """Sets the svpresact of this CasCompEcp.


        :param svpresact: The svpresact of this CasCompEcp.  # noqa: E501
        :type: OneOfCasCompEcpSvpresact
        """

        self._svpresact = svpresact

    @property
    def svpresset(self):
        """Gets the svpresset of this CasCompEcp.  # noqa: E501


        :return: The svpresset of this CasCompEcp.  # noqa: E501
        :rtype: OneOfCasCompEcpSvpresset
        """
        return self._svpresset

    @svpresset.setter
    def svpresset(self, svpresset):
        """Sets the svpresset of this CasCompEcp.


        :param svpresset: The svpresset of this CasCompEcp.  # noqa: E501
        :type: OneOfCasCompEcpSvpresset
        """

        self._svpresset = svpresset

    @property
    def syscreatedate(self):
        """Gets the syscreatedate of this CasCompEcp.  # noqa: E501


        :return: The syscreatedate of this CasCompEcp.  # noqa: E501
        :rtype: datetime
        """
        return self._syscreatedate

    @syscreatedate.setter
    def syscreatedate(self, syscreatedate):
        """Sets the syscreatedate of this CasCompEcp.


        :param syscreatedate: The syscreatedate of this CasCompEcp.  # noqa: E501
        :type: datetime
        """

        self._syscreatedate = syscreatedate

    @property
    def syscreateuser(self):
        """Gets the syscreateuser of this CasCompEcp.  # noqa: E501


        :return: The syscreateuser of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._syscreateuser

    @syscreateuser.setter
    def syscreateuser(self, syscreateuser):
        """Sets the syscreateuser of this CasCompEcp.


        :param syscreateuser: The syscreateuser of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._syscreateuser = syscreateuser

    @property
    def syslockchildren(self):
        """Gets the syslockchildren of this CasCompEcp.  # noqa: E501


        :return: The syslockchildren of this CasCompEcp.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildren

    @syslockchildren.setter
    def syslockchildren(self, syslockchildren):
        """Sets the syslockchildren of this CasCompEcp.


        :param syslockchildren: The syslockchildren of this CasCompEcp.  # noqa: E501
        :type: int
        """

        self._syslockchildren = syslockchildren

    @property
    def syslockchildrenui(self):
        """Gets the syslockchildrenui of this CasCompEcp.  # noqa: E501


        :return: The syslockchildrenui of this CasCompEcp.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildrenui

    @syslockchildrenui.setter
    def syslockchildrenui(self, syslockchildrenui):
        """Sets the syslockchildrenui of this CasCompEcp.


        :param syslockchildrenui: The syslockchildrenui of this CasCompEcp.  # noqa: E501
        :type: int
        """

        self._syslockchildrenui = syslockchildrenui

    @property
    def syslockdate(self):
        """Gets the syslockdate of this CasCompEcp.  # noqa: E501


        :return: The syslockdate of this CasCompEcp.  # noqa: E501
        :rtype: datetime
        """
        return self._syslockdate

    @syslockdate.setter
    def syslockdate(self, syslockdate):
        """Sets the syslockdate of this CasCompEcp.


        :param syslockdate: The syslockdate of this CasCompEcp.  # noqa: E501
        :type: datetime
        """

        self._syslockdate = syslockdate

    @property
    def syslockme(self):
        """Gets the syslockme of this CasCompEcp.  # noqa: E501


        :return: The syslockme of this CasCompEcp.  # noqa: E501
        :rtype: int
        """
        return self._syslockme

    @syslockme.setter
    def syslockme(self, syslockme):
        """Sets the syslockme of this CasCompEcp.


        :param syslockme: The syslockme of this CasCompEcp.  # noqa: E501
        :type: int
        """

        self._syslockme = syslockme

    @property
    def syslockmeui(self):
        """Gets the syslockmeui of this CasCompEcp.  # noqa: E501


        :return: The syslockmeui of this CasCompEcp.  # noqa: E501
        :rtype: int
        """
        return self._syslockmeui

    @syslockmeui.setter
    def syslockmeui(self, syslockmeui):
        """Sets the syslockmeui of this CasCompEcp.


        :param syslockmeui: The syslockmeui of this CasCompEcp.  # noqa: E501
        :type: int
        """

        self._syslockmeui = syslockmeui

    @property
    def sysmoddate(self):
        """Gets the sysmoddate of this CasCompEcp.  # noqa: E501


        :return: The sysmoddate of this CasCompEcp.  # noqa: E501
        :rtype: datetime
        """
        return self._sysmoddate

    @sysmoddate.setter
    def sysmoddate(self, sysmoddate):
        """Sets the sysmoddate of this CasCompEcp.


        :param sysmoddate: The sysmoddate of this CasCompEcp.  # noqa: E501
        :type: datetime
        """

        self._sysmoddate = sysmoddate

    @property
    def sysmoduser(self):
        """Gets the sysmoduser of this CasCompEcp.  # noqa: E501


        :return: The sysmoduser of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._sysmoduser

    @sysmoduser.setter
    def sysmoduser(self, sysmoduser):
        """Sets the sysmoduser of this CasCompEcp.


        :param sysmoduser: The sysmoduser of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._sysmoduser = sysmoduser

    @property
    def systag(self):
        """Gets the systag of this CasCompEcp.  # noqa: E501


        :return: The systag of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this CasCompEcp.


        :param systag: The systag of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._systag = systag

    @property
    def typ(self):
        """Gets the typ of this CasCompEcp.  # noqa: E501


        :return: The typ of this CasCompEcp.  # noqa: E501
        :rtype: str
        """
        return self._typ

    @typ.setter
    def typ(self, typ):
        """Sets the typ of this CasCompEcp.


        :param typ: The typ of this CasCompEcp.  # noqa: E501
        :type: str
        """

        self._typ = typ

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CasCompEcp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CasCompEcp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
