# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemathics/apis/type/shared/v1/book_updates.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3systemathics/apis/type/shared/v1/book_updates.proto\x12 systemathics.apis.type.shared.v1*k\n\x0b\x42ookUpdates\x12\x1c\n\x18\x42OOK_UPDATES_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x42OOK_UPDATES_SNAPSHOTS_ONLY\x10\x01\x12\x1d\n\x19\x42OOK_UPDATES_INCREMENTALS\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systemathics.apis.type.shared.v1.book_updates_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKUPDATES._serialized_start=89
  _BOOKUPDATES._serialized_end=196
# @@protoc_insertion_point(module_scope)
