import pandas as pd
from solas_disparity import const as const
from solas_disparity.types._stat_sig_test import StatSigTest as StatSigTest
from typing import Optional

class StatSig:
    stat_sig_test: StatSigTest
    p_values: pd.Series
    summary_table: pd.DataFrame
    t_statistics: Optional[pd.DataFrame]
    standard_errors: Optional[pd.DataFrame]
    @property
    def percent_missing(self) -> pd.DataFrame: ...
    def __init__(self, stat_sig_test, p_values, summary_table, t_statistics, standard_errors) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
