# coding: utf-8

"""
    Camunda Platform REST API

    OpenApi Spec for Camunda Platform REST API.  # noqa: E501

    The version of the OpenAPI document: 7.17.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from generic_camunda_client.configuration import Configuration


class DecisionRequirementsDefinitionXmlDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'dmn_xml': 'str'
    }

    attribute_map = {
        'id': 'id',
        'dmn_xml': 'dmnXml'
    }

    def __init__(self, id=None, dmn_xml=None, local_vars_configuration=None):  # noqa: E501
        """DecisionRequirementsDefinitionXmlDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._dmn_xml = None
        self.discriminator = None

        self.id = id
        self.dmn_xml = dmn_xml

    @property
    def id(self):
        """Gets the id of this DecisionRequirementsDefinitionXmlDto.  # noqa: E501

        The id of the decision requirements definition.  # noqa: E501

        :return: The id of this DecisionRequirementsDefinitionXmlDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DecisionRequirementsDefinitionXmlDto.

        The id of the decision requirements definition.  # noqa: E501

        :param id: The id of this DecisionRequirementsDefinitionXmlDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def dmn_xml(self):
        """Gets the dmn_xml of this DecisionRequirementsDefinitionXmlDto.  # noqa: E501

        An escaped XML string containing the XML that this decision requirements definition was deployed with. Carriage returns, line feeds and quotation marks are escaped.  # noqa: E501

        :return: The dmn_xml of this DecisionRequirementsDefinitionXmlDto.  # noqa: E501
        :rtype: str
        """
        return self._dmn_xml

    @dmn_xml.setter
    def dmn_xml(self, dmn_xml):
        """Sets the dmn_xml of this DecisionRequirementsDefinitionXmlDto.

        An escaped XML string containing the XML that this decision requirements definition was deployed with. Carriage returns, line feeds and quotation marks are escaped.  # noqa: E501

        :param dmn_xml: The dmn_xml of this DecisionRequirementsDefinitionXmlDto.  # noqa: E501
        :type: str
        """

        self._dmn_xml = dmn_xml

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DecisionRequirementsDefinitionXmlDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DecisionRequirementsDefinitionXmlDto):
            return True

        return self.to_dict() != other.to_dict()
