# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.risers_api import RisersApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestRisersApi(unittest.TestCase):
    """RisersApi unit test stubs"""

    def setUp(self):
        self.api = RisersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_riser(self):
        """Test case for get_riser

        Get entity from Risers by key  # noqa: E501
        """
        pass

    def test_list_riser(self):
        """Test case for list_riser

        Get entities from Risers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
