# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.prod_setting_flows_api import ProdSettingFlowsApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestProdSettingFlowsApi(unittest.TestCase):
    """ProdSettingFlowsApi unit test stubs"""

    def setUp(self):
        self.api = ProdSettingFlowsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_prod_setting_flow(self):
        """Test case for get_prod_setting_flow

        Get entity from ProdSettingFlows by key  # noqa: E501
        """
        pass

    def test_list_prod_setting_flow(self):
        """Test case for list_prod_setting_flow

        Get entities from ProdSettingFlows  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
