# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.models.one_of_fluid_analysis_pressamplerec import OneOfFluidAnalysisPressamplerec  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestOneOfFluidAnalysisPressamplerec(unittest.TestCase):
    """OneOfFluidAnalysisPressamplerec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfFluidAnalysisPressamplerec(self):
        """Test OneOfFluidAnalysisPressamplerec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wellview_odata_api.models.one_of_fluid_analysis_pressamplerec.OneOfFluidAnalysisPressamplerec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
