# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Agreement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agreement_contacts': 'list[AgreementContact]',
        'agreement_data_obls': 'list[AgreementDataObl]',
        'agreement_dates': 'list[AgreementDate]',
        'agreement_ints': 'list[AgreementInt]',
        'agreement_links': 'list[AgreementLink]',
        'com': 'str',
        'contractno': 'str',
        'des': 'str',
        'dttmend': 'datetime',
        'dttmstart': 'datetime',
        'dttmstatus': 'datetime',
        'idrec': 'str',
        'idwell': 'str',
        'refno': 'str',
        'status': 'str',
        'syscreatedate': 'datetime',
        'syscreateuser': 'str',
        'syslockchildren': 'int',
        'syslockchildrenui': 'int',
        'syslockdate': 'datetime',
        'syslockme': 'int',
        'syslockmeui': 'int',
        'sysmoddate': 'datetime',
        'sysmoduser': 'str',
        'systag': 'str',
        'typ1': 'str',
        'typ2': 'str',
        'wellheader': 'AnyOfAgreementWellheader'
    }

    attribute_map = {
        'agreement_contacts': 'agreementContacts',
        'agreement_data_obls': 'agreementDataObls',
        'agreement_dates': 'agreementDates',
        'agreement_ints': 'agreementInts',
        'agreement_links': 'agreementLinks',
        'com': 'com',
        'contractno': 'contractno',
        'des': 'des',
        'dttmend': 'dttmend',
        'dttmstart': 'dttmstart',
        'dttmstatus': 'dttmstatus',
        'idrec': 'idrec',
        'idwell': 'idwell',
        'refno': 'refno',
        'status': 'status',
        'syscreatedate': 'syscreatedate',
        'syscreateuser': 'syscreateuser',
        'syslockchildren': 'syslockchildren',
        'syslockchildrenui': 'syslockchildrenui',
        'syslockdate': 'syslockdate',
        'syslockme': 'syslockme',
        'syslockmeui': 'syslockmeui',
        'sysmoddate': 'sysmoddate',
        'sysmoduser': 'sysmoduser',
        'systag': 'systag',
        'typ1': 'typ1',
        'typ2': 'typ2',
        'wellheader': 'wellheader'
    }

    def __init__(self, agreement_contacts=None, agreement_data_obls=None, agreement_dates=None, agreement_ints=None, agreement_links=None, com=None, contractno=None, des=None, dttmend=None, dttmstart=None, dttmstatus=None, idrec=None, idwell=None, refno=None, status=None, syscreatedate=None, syscreateuser=None, syslockchildren=None, syslockchildrenui=None, syslockdate=None, syslockme=None, syslockmeui=None, sysmoddate=None, sysmoduser=None, systag=None, typ1=None, typ2=None, wellheader=None):  # noqa: E501
        """Agreement - a model defined in Swagger"""  # noqa: E501
        self._agreement_contacts = None
        self._agreement_data_obls = None
        self._agreement_dates = None
        self._agreement_ints = None
        self._agreement_links = None
        self._com = None
        self._contractno = None
        self._des = None
        self._dttmend = None
        self._dttmstart = None
        self._dttmstatus = None
        self._idrec = None
        self._idwell = None
        self._refno = None
        self._status = None
        self._syscreatedate = None
        self._syscreateuser = None
        self._syslockchildren = None
        self._syslockchildrenui = None
        self._syslockdate = None
        self._syslockme = None
        self._syslockmeui = None
        self._sysmoddate = None
        self._sysmoduser = None
        self._systag = None
        self._typ1 = None
        self._typ2 = None
        self._wellheader = None
        self.discriminator = None
        if agreement_contacts is not None:
            self.agreement_contacts = agreement_contacts
        if agreement_data_obls is not None:
            self.agreement_data_obls = agreement_data_obls
        if agreement_dates is not None:
            self.agreement_dates = agreement_dates
        if agreement_ints is not None:
            self.agreement_ints = agreement_ints
        if agreement_links is not None:
            self.agreement_links = agreement_links
        if com is not None:
            self.com = com
        if contractno is not None:
            self.contractno = contractno
        if des is not None:
            self.des = des
        if dttmend is not None:
            self.dttmend = dttmend
        if dttmstart is not None:
            self.dttmstart = dttmstart
        if dttmstatus is not None:
            self.dttmstatus = dttmstatus
        if idrec is not None:
            self.idrec = idrec
        if idwell is not None:
            self.idwell = idwell
        if refno is not None:
            self.refno = refno
        if status is not None:
            self.status = status
        if syscreatedate is not None:
            self.syscreatedate = syscreatedate
        if syscreateuser is not None:
            self.syscreateuser = syscreateuser
        if syslockchildren is not None:
            self.syslockchildren = syslockchildren
        if syslockchildrenui is not None:
            self.syslockchildrenui = syslockchildrenui
        if syslockdate is not None:
            self.syslockdate = syslockdate
        if syslockme is not None:
            self.syslockme = syslockme
        if syslockmeui is not None:
            self.syslockmeui = syslockmeui
        if sysmoddate is not None:
            self.sysmoddate = sysmoddate
        if sysmoduser is not None:
            self.sysmoduser = sysmoduser
        if systag is not None:
            self.systag = systag
        if typ1 is not None:
            self.typ1 = typ1
        if typ2 is not None:
            self.typ2 = typ2
        if wellheader is not None:
            self.wellheader = wellheader

    @property
    def agreement_contacts(self):
        """Gets the agreement_contacts of this Agreement.  # noqa: E501


        :return: The agreement_contacts of this Agreement.  # noqa: E501
        :rtype: list[AgreementContact]
        """
        return self._agreement_contacts

    @agreement_contacts.setter
    def agreement_contacts(self, agreement_contacts):
        """Sets the agreement_contacts of this Agreement.


        :param agreement_contacts: The agreement_contacts of this Agreement.  # noqa: E501
        :type: list[AgreementContact]
        """

        self._agreement_contacts = agreement_contacts

    @property
    def agreement_data_obls(self):
        """Gets the agreement_data_obls of this Agreement.  # noqa: E501


        :return: The agreement_data_obls of this Agreement.  # noqa: E501
        :rtype: list[AgreementDataObl]
        """
        return self._agreement_data_obls

    @agreement_data_obls.setter
    def agreement_data_obls(self, agreement_data_obls):
        """Sets the agreement_data_obls of this Agreement.


        :param agreement_data_obls: The agreement_data_obls of this Agreement.  # noqa: E501
        :type: list[AgreementDataObl]
        """

        self._agreement_data_obls = agreement_data_obls

    @property
    def agreement_dates(self):
        """Gets the agreement_dates of this Agreement.  # noqa: E501


        :return: The agreement_dates of this Agreement.  # noqa: E501
        :rtype: list[AgreementDate]
        """
        return self._agreement_dates

    @agreement_dates.setter
    def agreement_dates(self, agreement_dates):
        """Sets the agreement_dates of this Agreement.


        :param agreement_dates: The agreement_dates of this Agreement.  # noqa: E501
        :type: list[AgreementDate]
        """

        self._agreement_dates = agreement_dates

    @property
    def agreement_ints(self):
        """Gets the agreement_ints of this Agreement.  # noqa: E501


        :return: The agreement_ints of this Agreement.  # noqa: E501
        :rtype: list[AgreementInt]
        """
        return self._agreement_ints

    @agreement_ints.setter
    def agreement_ints(self, agreement_ints):
        """Sets the agreement_ints of this Agreement.


        :param agreement_ints: The agreement_ints of this Agreement.  # noqa: E501
        :type: list[AgreementInt]
        """

        self._agreement_ints = agreement_ints

    @property
    def agreement_links(self):
        """Gets the agreement_links of this Agreement.  # noqa: E501


        :return: The agreement_links of this Agreement.  # noqa: E501
        :rtype: list[AgreementLink]
        """
        return self._agreement_links

    @agreement_links.setter
    def agreement_links(self, agreement_links):
        """Sets the agreement_links of this Agreement.


        :param agreement_links: The agreement_links of this Agreement.  # noqa: E501
        :type: list[AgreementLink]
        """

        self._agreement_links = agreement_links

    @property
    def com(self):
        """Gets the com of this Agreement.  # noqa: E501


        :return: The com of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._com

    @com.setter
    def com(self, com):
        """Sets the com of this Agreement.


        :param com: The com of this Agreement.  # noqa: E501
        :type: str
        """

        self._com = com

    @property
    def contractno(self):
        """Gets the contractno of this Agreement.  # noqa: E501


        :return: The contractno of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._contractno

    @contractno.setter
    def contractno(self, contractno):
        """Sets the contractno of this Agreement.


        :param contractno: The contractno of this Agreement.  # noqa: E501
        :type: str
        """

        self._contractno = contractno

    @property
    def des(self):
        """Gets the des of this Agreement.  # noqa: E501


        :return: The des of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._des

    @des.setter
    def des(self, des):
        """Sets the des of this Agreement.


        :param des: The des of this Agreement.  # noqa: E501
        :type: str
        """

        self._des = des

    @property
    def dttmend(self):
        """Gets the dttmend of this Agreement.  # noqa: E501


        :return: The dttmend of this Agreement.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmend

    @dttmend.setter
    def dttmend(self, dttmend):
        """Sets the dttmend of this Agreement.


        :param dttmend: The dttmend of this Agreement.  # noqa: E501
        :type: datetime
        """

        self._dttmend = dttmend

    @property
    def dttmstart(self):
        """Gets the dttmstart of this Agreement.  # noqa: E501


        :return: The dttmstart of this Agreement.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmstart

    @dttmstart.setter
    def dttmstart(self, dttmstart):
        """Sets the dttmstart of this Agreement.


        :param dttmstart: The dttmstart of this Agreement.  # noqa: E501
        :type: datetime
        """

        self._dttmstart = dttmstart

    @property
    def dttmstatus(self):
        """Gets the dttmstatus of this Agreement.  # noqa: E501


        :return: The dttmstatus of this Agreement.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmstatus

    @dttmstatus.setter
    def dttmstatus(self, dttmstatus):
        """Sets the dttmstatus of this Agreement.


        :param dttmstatus: The dttmstatus of this Agreement.  # noqa: E501
        :type: datetime
        """

        self._dttmstatus = dttmstatus

    @property
    def idrec(self):
        """Gets the idrec of this Agreement.  # noqa: E501


        :return: The idrec of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this Agreement.


        :param idrec: The idrec of this Agreement.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idwell(self):
        """Gets the idwell of this Agreement.  # noqa: E501


        :return: The idwell of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this Agreement.


        :param idwell: The idwell of this Agreement.  # noqa: E501
        :type: str
        """

        self._idwell = idwell

    @property
    def refno(self):
        """Gets the refno of this Agreement.  # noqa: E501


        :return: The refno of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._refno

    @refno.setter
    def refno(self, refno):
        """Sets the refno of this Agreement.


        :param refno: The refno of this Agreement.  # noqa: E501
        :type: str
        """

        self._refno = refno

    @property
    def status(self):
        """Gets the status of this Agreement.  # noqa: E501


        :return: The status of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Agreement.


        :param status: The status of this Agreement.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def syscreatedate(self):
        """Gets the syscreatedate of this Agreement.  # noqa: E501


        :return: The syscreatedate of this Agreement.  # noqa: E501
        :rtype: datetime
        """
        return self._syscreatedate

    @syscreatedate.setter
    def syscreatedate(self, syscreatedate):
        """Sets the syscreatedate of this Agreement.


        :param syscreatedate: The syscreatedate of this Agreement.  # noqa: E501
        :type: datetime
        """

        self._syscreatedate = syscreatedate

    @property
    def syscreateuser(self):
        """Gets the syscreateuser of this Agreement.  # noqa: E501


        :return: The syscreateuser of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._syscreateuser

    @syscreateuser.setter
    def syscreateuser(self, syscreateuser):
        """Sets the syscreateuser of this Agreement.


        :param syscreateuser: The syscreateuser of this Agreement.  # noqa: E501
        :type: str
        """

        self._syscreateuser = syscreateuser

    @property
    def syslockchildren(self):
        """Gets the syslockchildren of this Agreement.  # noqa: E501


        :return: The syslockchildren of this Agreement.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildren

    @syslockchildren.setter
    def syslockchildren(self, syslockchildren):
        """Sets the syslockchildren of this Agreement.


        :param syslockchildren: The syslockchildren of this Agreement.  # noqa: E501
        :type: int
        """

        self._syslockchildren = syslockchildren

    @property
    def syslockchildrenui(self):
        """Gets the syslockchildrenui of this Agreement.  # noqa: E501


        :return: The syslockchildrenui of this Agreement.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildrenui

    @syslockchildrenui.setter
    def syslockchildrenui(self, syslockchildrenui):
        """Sets the syslockchildrenui of this Agreement.


        :param syslockchildrenui: The syslockchildrenui of this Agreement.  # noqa: E501
        :type: int
        """

        self._syslockchildrenui = syslockchildrenui

    @property
    def syslockdate(self):
        """Gets the syslockdate of this Agreement.  # noqa: E501


        :return: The syslockdate of this Agreement.  # noqa: E501
        :rtype: datetime
        """
        return self._syslockdate

    @syslockdate.setter
    def syslockdate(self, syslockdate):
        """Sets the syslockdate of this Agreement.


        :param syslockdate: The syslockdate of this Agreement.  # noqa: E501
        :type: datetime
        """

        self._syslockdate = syslockdate

    @property
    def syslockme(self):
        """Gets the syslockme of this Agreement.  # noqa: E501


        :return: The syslockme of this Agreement.  # noqa: E501
        :rtype: int
        """
        return self._syslockme

    @syslockme.setter
    def syslockme(self, syslockme):
        """Sets the syslockme of this Agreement.


        :param syslockme: The syslockme of this Agreement.  # noqa: E501
        :type: int
        """

        self._syslockme = syslockme

    @property
    def syslockmeui(self):
        """Gets the syslockmeui of this Agreement.  # noqa: E501


        :return: The syslockmeui of this Agreement.  # noqa: E501
        :rtype: int
        """
        return self._syslockmeui

    @syslockmeui.setter
    def syslockmeui(self, syslockmeui):
        """Sets the syslockmeui of this Agreement.


        :param syslockmeui: The syslockmeui of this Agreement.  # noqa: E501
        :type: int
        """

        self._syslockmeui = syslockmeui

    @property
    def sysmoddate(self):
        """Gets the sysmoddate of this Agreement.  # noqa: E501


        :return: The sysmoddate of this Agreement.  # noqa: E501
        :rtype: datetime
        """
        return self._sysmoddate

    @sysmoddate.setter
    def sysmoddate(self, sysmoddate):
        """Sets the sysmoddate of this Agreement.


        :param sysmoddate: The sysmoddate of this Agreement.  # noqa: E501
        :type: datetime
        """

        self._sysmoddate = sysmoddate

    @property
    def sysmoduser(self):
        """Gets the sysmoduser of this Agreement.  # noqa: E501


        :return: The sysmoduser of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._sysmoduser

    @sysmoduser.setter
    def sysmoduser(self, sysmoduser):
        """Sets the sysmoduser of this Agreement.


        :param sysmoduser: The sysmoduser of this Agreement.  # noqa: E501
        :type: str
        """

        self._sysmoduser = sysmoduser

    @property
    def systag(self):
        """Gets the systag of this Agreement.  # noqa: E501


        :return: The systag of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this Agreement.


        :param systag: The systag of this Agreement.  # noqa: E501
        :type: str
        """

        self._systag = systag

    @property
    def typ1(self):
        """Gets the typ1 of this Agreement.  # noqa: E501


        :return: The typ1 of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._typ1

    @typ1.setter
    def typ1(self, typ1):
        """Sets the typ1 of this Agreement.


        :param typ1: The typ1 of this Agreement.  # noqa: E501
        :type: str
        """

        self._typ1 = typ1

    @property
    def typ2(self):
        """Gets the typ2 of this Agreement.  # noqa: E501


        :return: The typ2 of this Agreement.  # noqa: E501
        :rtype: str
        """
        return self._typ2

    @typ2.setter
    def typ2(self, typ2):
        """Sets the typ2 of this Agreement.


        :param typ2: The typ2 of this Agreement.  # noqa: E501
        :type: str
        """

        self._typ2 = typ2

    @property
    def wellheader(self):
        """Gets the wellheader of this Agreement.  # noqa: E501


        :return: The wellheader of this Agreement.  # noqa: E501
        :rtype: AnyOfAgreementWellheader
        """
        return self._wellheader

    @wellheader.setter
    def wellheader(self, wellheader):
        """Sets the wellheader of this Agreement.


        :param wellheader: The wellheader of this Agreement.  # noqa: E501
        :type: AnyOfAgreementWellheader
        """

        self._wellheader = wellheader

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Agreement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Agreement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
