
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-24T15:09:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4ce3a8faec19363574fb619329668b5cf926490",
 "version": "2.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
