# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.fluid_analysis_oil_vis_api import FluidAnalysisOilVisApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestFluidAnalysisOilVisApi(unittest.TestCase):
    """FluidAnalysisOilVisApi unit test stubs"""

    def setUp(self):
        self.api = FluidAnalysisOilVisApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fluid_analysis_oil_vis(self):
        """Test case for get_fluid_analysis_oil_vis

        Get entity from FluidAnalysisOilVis by key  # noqa: E501
        """
        pass

    def test_list_fluid_analysis_oil_vis(self):
        """Test case for list_fluid_analysis_oil_vis

        Get entities from FluidAnalysisOilVis  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
