# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.swab_details_api import SwabDetailsApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestSwabDetailsApi(unittest.TestCase):
    """SwabDetailsApi unit test stubs"""

    def setUp(self):
        self.api = SwabDetailsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_swab_details(self):
        """Test case for get_swab_details

        Get entity from SwabDetails by key  # noqa: E501
        """
        pass

    def test_list_swab_details(self):
        """Test case for list_swab_details

        Get entities from SwabDetails  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
