# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Generated by: https://openapi-generator.tech
"""

import unittest

import wellview_sdk_api
from wellview_sdk_api.model.sidewall_core_data import SidewallCoreData
from wellview_sdk_api import configuration


class TestSidewallCoreData(unittest.TestCase):
    """SidewallCoreData unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
