# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.models.any_of_tub_comp_sssv_insert_tub_comp_sssv import AnyOfTubCompSssvInsertTubCompSssv  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestAnyOfTubCompSssvInsertTubCompSssv(unittest.TestCase):
    """AnyOfTubCompSssvInsertTubCompSssv unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfTubCompSssvInsertTubCompSssv(self):
        """Test AnyOfTubCompSssvInsertTubCompSssv"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wellview_odata_api.models.any_of_tub_comp_sssv_insert_tub_comp_sssv.AnyOfTubCompSssvInsertTubCompSssv()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
