# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_odata_api
from wellview_odata_api.api.job_safety_incident_actions_api import JobSafetyIncidentActionsApi  # noqa: E501
from wellview_odata_api.rest import ApiException


class TestJobSafetyIncidentActionsApi(unittest.TestCase):
    """JobSafetyIncidentActionsApi unit test stubs"""

    def setUp(self):
        self.api = JobSafetyIncidentActionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job_safety_incident_action(self):
        """Test case for get_job_safety_incident_action

        Get entity from JobSafetyIncidentActions by key  # noqa: E501
        """
        pass

    def test_list_job_safety_incident_action(self):
        """Test case for list_job_safety_incident_action

        Get entities from JobSafetyIncidentActions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
