class ScoreLabel:
    ORG = "ORG"
    LOC = "LOC"
    MON = "MON"
    ETH = "ETH"
    URL = "URL"
    PER = "PER"
    NUMB = "NUMB"
    MED = "MED"
    MISC = "MISC"
    YEAR = "YEAR"
    LIST = "LIST"
    CARD_NR = "CARD_NR"
    ACC_NR = "ACC_NR"
    PER_NR = "PER_NR"
