
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-28T14:15:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2fb32e3a8246e85538bd74d4cdc765e510c14bd9",
 "version": "0.15.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
