# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from wellview_sdk_api import schemas  # noqa: F401


class WellViewTableStructure(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            Id = schemas.StrSchema
            UserPrincipalName = schemas.StrSchema
            
            
            class Tables(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['WellViewTableAction']:
                        return WellViewTableAction
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['WellViewTableAction'], typing.List['WellViewTableAction']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Tables':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'WellViewTableAction':
                    return super().__getitem__(i)
            __annotations__ = {
                "Id": Id,
                "UserPrincipalName": UserPrincipalName,
                "Tables": Tables,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Id"]) -> MetaOapg.properties.Id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["UserPrincipalName"]) -> MetaOapg.properties.UserPrincipalName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Tables"]) -> MetaOapg.properties.Tables: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Id", "UserPrincipalName", "Tables", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Id"]) -> typing.Union[MetaOapg.properties.Id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["UserPrincipalName"]) -> typing.Union[MetaOapg.properties.UserPrincipalName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Tables"]) -> typing.Union[MetaOapg.properties.Tables, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Id", "UserPrincipalName", "Tables", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Id: typing.Union[MetaOapg.properties.Id, str, schemas.Unset] = schemas.unset,
        UserPrincipalName: typing.Union[MetaOapg.properties.UserPrincipalName, str, schemas.Unset] = schemas.unset,
        Tables: typing.Union[MetaOapg.properties.Tables, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WellViewTableStructure':
        return super().__new__(
            cls,
            *args,
            Id=Id,
            UserPrincipalName=UserPrincipalName,
            Tables=Tables,
            _configuration=_configuration,
            **kwargs,
        )

from wellview_sdk_api.model.well_view_table_action import WellViewTableAction
