# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobRigSolidsCentCyc(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'com': 'str',
        'dttmend': 'datetime',
        'dttmmanufacture': 'datetime',
        'dttmstart': 'datetime',
        'idrec': 'str',
        'idrecparent': 'str',
        'idwell': 'str',
        'job_rig': 'AnyOfJobRigSolidsCentCycJobRig',
        'job_rig_solids_cent_cyc_chks': 'list[JobRigSolidsCentCycChk]',
        'make': 'str',
        'model': 'str',
        'qty': 'int',
        'refid': 'str',
        'sn': 'str',
        'syscreatedate': 'datetime',
        'syscreateuser': 'str',
        'syslockchildren': 'int',
        'syslockchildrenui': 'int',
        'syslockdate': 'datetime',
        'syslockme': 'int',
        'syslockmeui': 'int',
        'sysmoddate': 'datetime',
        'sysmoduser': 'str',
        'systag': 'str',
        'szdia': 'OneOfJobRigSolidsCentCycSzdia',
        'typ': 'str'
    }

    attribute_map = {
        'com': 'com',
        'dttmend': 'dttmend',
        'dttmmanufacture': 'dttmmanufacture',
        'dttmstart': 'dttmstart',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idwell': 'idwell',
        'job_rig': 'jobRig',
        'job_rig_solids_cent_cyc_chks': 'jobRigSolidsCentCycChks',
        'make': 'make',
        'model': 'model',
        'qty': 'qty',
        'refid': 'refid',
        'sn': 'sn',
        'syscreatedate': 'syscreatedate',
        'syscreateuser': 'syscreateuser',
        'syslockchildren': 'syslockchildren',
        'syslockchildrenui': 'syslockchildrenui',
        'syslockdate': 'syslockdate',
        'syslockme': 'syslockme',
        'syslockmeui': 'syslockmeui',
        'sysmoddate': 'sysmoddate',
        'sysmoduser': 'sysmoduser',
        'systag': 'systag',
        'szdia': 'szdia',
        'typ': 'typ'
    }

    def __init__(self, com=None, dttmend=None, dttmmanufacture=None, dttmstart=None, idrec=None, idrecparent=None, idwell=None, job_rig=None, job_rig_solids_cent_cyc_chks=None, make=None, model=None, qty=None, refid=None, sn=None, syscreatedate=None, syscreateuser=None, syslockchildren=None, syslockchildrenui=None, syslockdate=None, syslockme=None, syslockmeui=None, sysmoddate=None, sysmoduser=None, systag=None, szdia=None, typ=None):  # noqa: E501
        """JobRigSolidsCentCyc - a model defined in Swagger"""  # noqa: E501
        self._com = None
        self._dttmend = None
        self._dttmmanufacture = None
        self._dttmstart = None
        self._idrec = None
        self._idrecparent = None
        self._idwell = None
        self._job_rig = None
        self._job_rig_solids_cent_cyc_chks = None
        self._make = None
        self._model = None
        self._qty = None
        self._refid = None
        self._sn = None
        self._syscreatedate = None
        self._syscreateuser = None
        self._syslockchildren = None
        self._syslockchildrenui = None
        self._syslockdate = None
        self._syslockme = None
        self._syslockmeui = None
        self._sysmoddate = None
        self._sysmoduser = None
        self._systag = None
        self._szdia = None
        self._typ = None
        self.discriminator = None
        if com is not None:
            self.com = com
        if dttmend is not None:
            self.dttmend = dttmend
        if dttmmanufacture is not None:
            self.dttmmanufacture = dttmmanufacture
        if dttmstart is not None:
            self.dttmstart = dttmstart
        if idrec is not None:
            self.idrec = idrec
        if idrecparent is not None:
            self.idrecparent = idrecparent
        if idwell is not None:
            self.idwell = idwell
        if job_rig is not None:
            self.job_rig = job_rig
        if job_rig_solids_cent_cyc_chks is not None:
            self.job_rig_solids_cent_cyc_chks = job_rig_solids_cent_cyc_chks
        if make is not None:
            self.make = make
        if model is not None:
            self.model = model
        if qty is not None:
            self.qty = qty
        if refid is not None:
            self.refid = refid
        if sn is not None:
            self.sn = sn
        if syscreatedate is not None:
            self.syscreatedate = syscreatedate
        if syscreateuser is not None:
            self.syscreateuser = syscreateuser
        if syslockchildren is not None:
            self.syslockchildren = syslockchildren
        if syslockchildrenui is not None:
            self.syslockchildrenui = syslockchildrenui
        if syslockdate is not None:
            self.syslockdate = syslockdate
        if syslockme is not None:
            self.syslockme = syslockme
        if syslockmeui is not None:
            self.syslockmeui = syslockmeui
        if sysmoddate is not None:
            self.sysmoddate = sysmoddate
        if sysmoduser is not None:
            self.sysmoduser = sysmoduser
        if systag is not None:
            self.systag = systag
        if szdia is not None:
            self.szdia = szdia
        if typ is not None:
            self.typ = typ

    @property
    def com(self):
        """Gets the com of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The com of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._com

    @com.setter
    def com(self, com):
        """Sets the com of this JobRigSolidsCentCyc.


        :param com: The com of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._com = com

    @property
    def dttmend(self):
        """Gets the dttmend of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The dttmend of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmend

    @dttmend.setter
    def dttmend(self, dttmend):
        """Sets the dttmend of this JobRigSolidsCentCyc.


        :param dttmend: The dttmend of this JobRigSolidsCentCyc.  # noqa: E501
        :type: datetime
        """

        self._dttmend = dttmend

    @property
    def dttmmanufacture(self):
        """Gets the dttmmanufacture of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The dttmmanufacture of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmmanufacture

    @dttmmanufacture.setter
    def dttmmanufacture(self, dttmmanufacture):
        """Sets the dttmmanufacture of this JobRigSolidsCentCyc.


        :param dttmmanufacture: The dttmmanufacture of this JobRigSolidsCentCyc.  # noqa: E501
        :type: datetime
        """

        self._dttmmanufacture = dttmmanufacture

    @property
    def dttmstart(self):
        """Gets the dttmstart of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The dttmstart of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmstart

    @dttmstart.setter
    def dttmstart(self, dttmstart):
        """Sets the dttmstart of this JobRigSolidsCentCyc.


        :param dttmstart: The dttmstart of this JobRigSolidsCentCyc.  # noqa: E501
        :type: datetime
        """

        self._dttmstart = dttmstart

    @property
    def idrec(self):
        """Gets the idrec of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The idrec of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this JobRigSolidsCentCyc.


        :param idrec: The idrec of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The idrecparent of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this JobRigSolidsCentCyc.


        :param idrecparent: The idrecparent of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._idrecparent = idrecparent

    @property
    def idwell(self):
        """Gets the idwell of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The idwell of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this JobRigSolidsCentCyc.


        :param idwell: The idwell of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._idwell = idwell

    @property
    def job_rig(self):
        """Gets the job_rig of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The job_rig of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: AnyOfJobRigSolidsCentCycJobRig
        """
        return self._job_rig

    @job_rig.setter
    def job_rig(self, job_rig):
        """Sets the job_rig of this JobRigSolidsCentCyc.


        :param job_rig: The job_rig of this JobRigSolidsCentCyc.  # noqa: E501
        :type: AnyOfJobRigSolidsCentCycJobRig
        """

        self._job_rig = job_rig

    @property
    def job_rig_solids_cent_cyc_chks(self):
        """Gets the job_rig_solids_cent_cyc_chks of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The job_rig_solids_cent_cyc_chks of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: list[JobRigSolidsCentCycChk]
        """
        return self._job_rig_solids_cent_cyc_chks

    @job_rig_solids_cent_cyc_chks.setter
    def job_rig_solids_cent_cyc_chks(self, job_rig_solids_cent_cyc_chks):
        """Sets the job_rig_solids_cent_cyc_chks of this JobRigSolidsCentCyc.


        :param job_rig_solids_cent_cyc_chks: The job_rig_solids_cent_cyc_chks of this JobRigSolidsCentCyc.  # noqa: E501
        :type: list[JobRigSolidsCentCycChk]
        """

        self._job_rig_solids_cent_cyc_chks = job_rig_solids_cent_cyc_chks

    @property
    def make(self):
        """Gets the make of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The make of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._make

    @make.setter
    def make(self, make):
        """Sets the make of this JobRigSolidsCentCyc.


        :param make: The make of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._make = make

    @property
    def model(self):
        """Gets the model of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The model of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this JobRigSolidsCentCyc.


        :param model: The model of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._model = model

    @property
    def qty(self):
        """Gets the qty of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The qty of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: int
        """
        return self._qty

    @qty.setter
    def qty(self, qty):
        """Sets the qty of this JobRigSolidsCentCyc.


        :param qty: The qty of this JobRigSolidsCentCyc.  # noqa: E501
        :type: int
        """

        self._qty = qty

    @property
    def refid(self):
        """Gets the refid of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The refid of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._refid

    @refid.setter
    def refid(self, refid):
        """Sets the refid of this JobRigSolidsCentCyc.


        :param refid: The refid of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._refid = refid

    @property
    def sn(self):
        """Gets the sn of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The sn of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._sn

    @sn.setter
    def sn(self, sn):
        """Sets the sn of this JobRigSolidsCentCyc.


        :param sn: The sn of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._sn = sn

    @property
    def syscreatedate(self):
        """Gets the syscreatedate of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The syscreatedate of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: datetime
        """
        return self._syscreatedate

    @syscreatedate.setter
    def syscreatedate(self, syscreatedate):
        """Sets the syscreatedate of this JobRigSolidsCentCyc.


        :param syscreatedate: The syscreatedate of this JobRigSolidsCentCyc.  # noqa: E501
        :type: datetime
        """

        self._syscreatedate = syscreatedate

    @property
    def syscreateuser(self):
        """Gets the syscreateuser of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The syscreateuser of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._syscreateuser

    @syscreateuser.setter
    def syscreateuser(self, syscreateuser):
        """Sets the syscreateuser of this JobRigSolidsCentCyc.


        :param syscreateuser: The syscreateuser of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._syscreateuser = syscreateuser

    @property
    def syslockchildren(self):
        """Gets the syslockchildren of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The syslockchildren of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildren

    @syslockchildren.setter
    def syslockchildren(self, syslockchildren):
        """Sets the syslockchildren of this JobRigSolidsCentCyc.


        :param syslockchildren: The syslockchildren of this JobRigSolidsCentCyc.  # noqa: E501
        :type: int
        """

        self._syslockchildren = syslockchildren

    @property
    def syslockchildrenui(self):
        """Gets the syslockchildrenui of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The syslockchildrenui of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildrenui

    @syslockchildrenui.setter
    def syslockchildrenui(self, syslockchildrenui):
        """Sets the syslockchildrenui of this JobRigSolidsCentCyc.


        :param syslockchildrenui: The syslockchildrenui of this JobRigSolidsCentCyc.  # noqa: E501
        :type: int
        """

        self._syslockchildrenui = syslockchildrenui

    @property
    def syslockdate(self):
        """Gets the syslockdate of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The syslockdate of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: datetime
        """
        return self._syslockdate

    @syslockdate.setter
    def syslockdate(self, syslockdate):
        """Sets the syslockdate of this JobRigSolidsCentCyc.


        :param syslockdate: The syslockdate of this JobRigSolidsCentCyc.  # noqa: E501
        :type: datetime
        """

        self._syslockdate = syslockdate

    @property
    def syslockme(self):
        """Gets the syslockme of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The syslockme of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: int
        """
        return self._syslockme

    @syslockme.setter
    def syslockme(self, syslockme):
        """Sets the syslockme of this JobRigSolidsCentCyc.


        :param syslockme: The syslockme of this JobRigSolidsCentCyc.  # noqa: E501
        :type: int
        """

        self._syslockme = syslockme

    @property
    def syslockmeui(self):
        """Gets the syslockmeui of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The syslockmeui of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: int
        """
        return self._syslockmeui

    @syslockmeui.setter
    def syslockmeui(self, syslockmeui):
        """Sets the syslockmeui of this JobRigSolidsCentCyc.


        :param syslockmeui: The syslockmeui of this JobRigSolidsCentCyc.  # noqa: E501
        :type: int
        """

        self._syslockmeui = syslockmeui

    @property
    def sysmoddate(self):
        """Gets the sysmoddate of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The sysmoddate of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: datetime
        """
        return self._sysmoddate

    @sysmoddate.setter
    def sysmoddate(self, sysmoddate):
        """Sets the sysmoddate of this JobRigSolidsCentCyc.


        :param sysmoddate: The sysmoddate of this JobRigSolidsCentCyc.  # noqa: E501
        :type: datetime
        """

        self._sysmoddate = sysmoddate

    @property
    def sysmoduser(self):
        """Gets the sysmoduser of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The sysmoduser of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._sysmoduser

    @sysmoduser.setter
    def sysmoduser(self, sysmoduser):
        """Sets the sysmoduser of this JobRigSolidsCentCyc.


        :param sysmoduser: The sysmoduser of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._sysmoduser = sysmoduser

    @property
    def systag(self):
        """Gets the systag of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The systag of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this JobRigSolidsCentCyc.


        :param systag: The systag of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._systag = systag

    @property
    def szdia(self):
        """Gets the szdia of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The szdia of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: OneOfJobRigSolidsCentCycSzdia
        """
        return self._szdia

    @szdia.setter
    def szdia(self, szdia):
        """Sets the szdia of this JobRigSolidsCentCyc.


        :param szdia: The szdia of this JobRigSolidsCentCyc.  # noqa: E501
        :type: OneOfJobRigSolidsCentCycSzdia
        """

        self._szdia = szdia

    @property
    def typ(self):
        """Gets the typ of this JobRigSolidsCentCyc.  # noqa: E501


        :return: The typ of this JobRigSolidsCentCyc.  # noqa: E501
        :rtype: str
        """
        return self._typ

    @typ.setter
    def typ(self, typ):
        """Sets the typ of this JobRigSolidsCentCyc.


        :param typ: The typ of this JobRigSolidsCentCyc.  # noqa: E501
        :type: str
        """

        self._typ = typ

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobRigSolidsCentCyc, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobRigSolidsCentCyc):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
