# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LogTool(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'com': 'str',
        'dttmcalibrate': 'datetime',
        'idrec': 'str',
        'idrecparent': 'str',
        'idwell': 'str',
        'log': 'AnyOfLogToolLog',
        'sn': 'str',
        'syscreatedate': 'datetime',
        'syscreateuser': 'str',
        'syslockchildren': 'int',
        'syslockchildrenui': 'int',
        'syslockdate': 'datetime',
        'syslockme': 'int',
        'syslockmeui': 'int',
        'sysmoddate': 'datetime',
        'sysmoduser': 'str',
        'systag': 'str',
        'tooltyp1': 'str',
        'tooltyp2': 'str'
    }

    attribute_map = {
        'com': 'com',
        'dttmcalibrate': 'dttmcalibrate',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idwell': 'idwell',
        'log': 'log',
        'sn': 'sn',
        'syscreatedate': 'syscreatedate',
        'syscreateuser': 'syscreateuser',
        'syslockchildren': 'syslockchildren',
        'syslockchildrenui': 'syslockchildrenui',
        'syslockdate': 'syslockdate',
        'syslockme': 'syslockme',
        'syslockmeui': 'syslockmeui',
        'sysmoddate': 'sysmoddate',
        'sysmoduser': 'sysmoduser',
        'systag': 'systag',
        'tooltyp1': 'tooltyp1',
        'tooltyp2': 'tooltyp2'
    }

    def __init__(self, com=None, dttmcalibrate=None, idrec=None, idrecparent=None, idwell=None, log=None, sn=None, syscreatedate=None, syscreateuser=None, syslockchildren=None, syslockchildrenui=None, syslockdate=None, syslockme=None, syslockmeui=None, sysmoddate=None, sysmoduser=None, systag=None, tooltyp1=None, tooltyp2=None):  # noqa: E501
        """LogTool - a model defined in Swagger"""  # noqa: E501
        self._com = None
        self._dttmcalibrate = None
        self._idrec = None
        self._idrecparent = None
        self._idwell = None
        self._log = None
        self._sn = None
        self._syscreatedate = None
        self._syscreateuser = None
        self._syslockchildren = None
        self._syslockchildrenui = None
        self._syslockdate = None
        self._syslockme = None
        self._syslockmeui = None
        self._sysmoddate = None
        self._sysmoduser = None
        self._systag = None
        self._tooltyp1 = None
        self._tooltyp2 = None
        self.discriminator = None
        if com is not None:
            self.com = com
        if dttmcalibrate is not None:
            self.dttmcalibrate = dttmcalibrate
        if idrec is not None:
            self.idrec = idrec
        if idrecparent is not None:
            self.idrecparent = idrecparent
        if idwell is not None:
            self.idwell = idwell
        if log is not None:
            self.log = log
        if sn is not None:
            self.sn = sn
        if syscreatedate is not None:
            self.syscreatedate = syscreatedate
        if syscreateuser is not None:
            self.syscreateuser = syscreateuser
        if syslockchildren is not None:
            self.syslockchildren = syslockchildren
        if syslockchildrenui is not None:
            self.syslockchildrenui = syslockchildrenui
        if syslockdate is not None:
            self.syslockdate = syslockdate
        if syslockme is not None:
            self.syslockme = syslockme
        if syslockmeui is not None:
            self.syslockmeui = syslockmeui
        if sysmoddate is not None:
            self.sysmoddate = sysmoddate
        if sysmoduser is not None:
            self.sysmoduser = sysmoduser
        if systag is not None:
            self.systag = systag
        if tooltyp1 is not None:
            self.tooltyp1 = tooltyp1
        if tooltyp2 is not None:
            self.tooltyp2 = tooltyp2

    @property
    def com(self):
        """Gets the com of this LogTool.  # noqa: E501


        :return: The com of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._com

    @com.setter
    def com(self, com):
        """Sets the com of this LogTool.


        :param com: The com of this LogTool.  # noqa: E501
        :type: str
        """

        self._com = com

    @property
    def dttmcalibrate(self):
        """Gets the dttmcalibrate of this LogTool.  # noqa: E501


        :return: The dttmcalibrate of this LogTool.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmcalibrate

    @dttmcalibrate.setter
    def dttmcalibrate(self, dttmcalibrate):
        """Sets the dttmcalibrate of this LogTool.


        :param dttmcalibrate: The dttmcalibrate of this LogTool.  # noqa: E501
        :type: datetime
        """

        self._dttmcalibrate = dttmcalibrate

    @property
    def idrec(self):
        """Gets the idrec of this LogTool.  # noqa: E501


        :return: The idrec of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this LogTool.


        :param idrec: The idrec of this LogTool.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this LogTool.  # noqa: E501


        :return: The idrecparent of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this LogTool.


        :param idrecparent: The idrecparent of this LogTool.  # noqa: E501
        :type: str
        """

        self._idrecparent = idrecparent

    @property
    def idwell(self):
        """Gets the idwell of this LogTool.  # noqa: E501


        :return: The idwell of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this LogTool.


        :param idwell: The idwell of this LogTool.  # noqa: E501
        :type: str
        """

        self._idwell = idwell

    @property
    def log(self):
        """Gets the log of this LogTool.  # noqa: E501


        :return: The log of this LogTool.  # noqa: E501
        :rtype: AnyOfLogToolLog
        """
        return self._log

    @log.setter
    def log(self, log):
        """Sets the log of this LogTool.


        :param log: The log of this LogTool.  # noqa: E501
        :type: AnyOfLogToolLog
        """

        self._log = log

    @property
    def sn(self):
        """Gets the sn of this LogTool.  # noqa: E501


        :return: The sn of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._sn

    @sn.setter
    def sn(self, sn):
        """Sets the sn of this LogTool.


        :param sn: The sn of this LogTool.  # noqa: E501
        :type: str
        """

        self._sn = sn

    @property
    def syscreatedate(self):
        """Gets the syscreatedate of this LogTool.  # noqa: E501


        :return: The syscreatedate of this LogTool.  # noqa: E501
        :rtype: datetime
        """
        return self._syscreatedate

    @syscreatedate.setter
    def syscreatedate(self, syscreatedate):
        """Sets the syscreatedate of this LogTool.


        :param syscreatedate: The syscreatedate of this LogTool.  # noqa: E501
        :type: datetime
        """

        self._syscreatedate = syscreatedate

    @property
    def syscreateuser(self):
        """Gets the syscreateuser of this LogTool.  # noqa: E501


        :return: The syscreateuser of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._syscreateuser

    @syscreateuser.setter
    def syscreateuser(self, syscreateuser):
        """Sets the syscreateuser of this LogTool.


        :param syscreateuser: The syscreateuser of this LogTool.  # noqa: E501
        :type: str
        """

        self._syscreateuser = syscreateuser

    @property
    def syslockchildren(self):
        """Gets the syslockchildren of this LogTool.  # noqa: E501


        :return: The syslockchildren of this LogTool.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildren

    @syslockchildren.setter
    def syslockchildren(self, syslockchildren):
        """Sets the syslockchildren of this LogTool.


        :param syslockchildren: The syslockchildren of this LogTool.  # noqa: E501
        :type: int
        """

        self._syslockchildren = syslockchildren

    @property
    def syslockchildrenui(self):
        """Gets the syslockchildrenui of this LogTool.  # noqa: E501


        :return: The syslockchildrenui of this LogTool.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildrenui

    @syslockchildrenui.setter
    def syslockchildrenui(self, syslockchildrenui):
        """Sets the syslockchildrenui of this LogTool.


        :param syslockchildrenui: The syslockchildrenui of this LogTool.  # noqa: E501
        :type: int
        """

        self._syslockchildrenui = syslockchildrenui

    @property
    def syslockdate(self):
        """Gets the syslockdate of this LogTool.  # noqa: E501


        :return: The syslockdate of this LogTool.  # noqa: E501
        :rtype: datetime
        """
        return self._syslockdate

    @syslockdate.setter
    def syslockdate(self, syslockdate):
        """Sets the syslockdate of this LogTool.


        :param syslockdate: The syslockdate of this LogTool.  # noqa: E501
        :type: datetime
        """

        self._syslockdate = syslockdate

    @property
    def syslockme(self):
        """Gets the syslockme of this LogTool.  # noqa: E501


        :return: The syslockme of this LogTool.  # noqa: E501
        :rtype: int
        """
        return self._syslockme

    @syslockme.setter
    def syslockme(self, syslockme):
        """Sets the syslockme of this LogTool.


        :param syslockme: The syslockme of this LogTool.  # noqa: E501
        :type: int
        """

        self._syslockme = syslockme

    @property
    def syslockmeui(self):
        """Gets the syslockmeui of this LogTool.  # noqa: E501


        :return: The syslockmeui of this LogTool.  # noqa: E501
        :rtype: int
        """
        return self._syslockmeui

    @syslockmeui.setter
    def syslockmeui(self, syslockmeui):
        """Sets the syslockmeui of this LogTool.


        :param syslockmeui: The syslockmeui of this LogTool.  # noqa: E501
        :type: int
        """

        self._syslockmeui = syslockmeui

    @property
    def sysmoddate(self):
        """Gets the sysmoddate of this LogTool.  # noqa: E501


        :return: The sysmoddate of this LogTool.  # noqa: E501
        :rtype: datetime
        """
        return self._sysmoddate

    @sysmoddate.setter
    def sysmoddate(self, sysmoddate):
        """Sets the sysmoddate of this LogTool.


        :param sysmoddate: The sysmoddate of this LogTool.  # noqa: E501
        :type: datetime
        """

        self._sysmoddate = sysmoddate

    @property
    def sysmoduser(self):
        """Gets the sysmoduser of this LogTool.  # noqa: E501


        :return: The sysmoduser of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._sysmoduser

    @sysmoduser.setter
    def sysmoduser(self, sysmoduser):
        """Sets the sysmoduser of this LogTool.


        :param sysmoduser: The sysmoduser of this LogTool.  # noqa: E501
        :type: str
        """

        self._sysmoduser = sysmoduser

    @property
    def systag(self):
        """Gets the systag of this LogTool.  # noqa: E501


        :return: The systag of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this LogTool.


        :param systag: The systag of this LogTool.  # noqa: E501
        :type: str
        """

        self._systag = systag

    @property
    def tooltyp1(self):
        """Gets the tooltyp1 of this LogTool.  # noqa: E501


        :return: The tooltyp1 of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._tooltyp1

    @tooltyp1.setter
    def tooltyp1(self, tooltyp1):
        """Sets the tooltyp1 of this LogTool.


        :param tooltyp1: The tooltyp1 of this LogTool.  # noqa: E501
        :type: str
        """

        self._tooltyp1 = tooltyp1

    @property
    def tooltyp2(self):
        """Gets the tooltyp2 of this LogTool.  # noqa: E501


        :return: The tooltyp2 of this LogTool.  # noqa: E501
        :rtype: str
        """
        return self._tooltyp2

    @tooltyp2.setter
    def tooltyp2(self, tooltyp2):
        """Sets the tooltyp2 of this LogTool.


        :param tooltyp2: The tooltyp2 of this LogTool.  # noqa: E501
        :type: str
        """

        self._tooltyp2 = tooltyp2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LogTool, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LogTool):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
