# coding: utf-8

"""
    OData Service for namespace Default

    This OData service is located at http://localhost  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobReportContacts(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'idrec': 'str',
        'idrecjobcontact': 'str',
        'idrecjobcontacttk': 'str',
        'idrecparent': 'str',
        'idwell': 'str',
        'job_report': 'AnyOfJobReportContactsJobReport',
        'pos': 'str',
        'syscarryfwdp': 'int',
        'syscreatedate': 'datetime',
        'syscreateuser': 'str',
        'syslockchildren': 'int',
        'syslockchildrenui': 'int',
        'syslockdate': 'datetime',
        'syslockme': 'int',
        'syslockmeui': 'int',
        'sysmoddate': 'datetime',
        'sysmoduser': 'str',
        'sysseq': 'int',
        'systag': 'str'
    }

    attribute_map = {
        'idrec': 'idrec',
        'idrecjobcontact': 'idrecjobcontact',
        'idrecjobcontacttk': 'idrecjobcontacttk',
        'idrecparent': 'idrecparent',
        'idwell': 'idwell',
        'job_report': 'jobReport',
        'pos': 'pos',
        'syscarryfwdp': 'syscarryfwdp',
        'syscreatedate': 'syscreatedate',
        'syscreateuser': 'syscreateuser',
        'syslockchildren': 'syslockchildren',
        'syslockchildrenui': 'syslockchildrenui',
        'syslockdate': 'syslockdate',
        'syslockme': 'syslockme',
        'syslockmeui': 'syslockmeui',
        'sysmoddate': 'sysmoddate',
        'sysmoduser': 'sysmoduser',
        'sysseq': 'sysseq',
        'systag': 'systag'
    }

    def __init__(self, idrec=None, idrecjobcontact=None, idrecjobcontacttk=None, idrecparent=None, idwell=None, job_report=None, pos=None, syscarryfwdp=None, syscreatedate=None, syscreateuser=None, syslockchildren=None, syslockchildrenui=None, syslockdate=None, syslockme=None, syslockmeui=None, sysmoddate=None, sysmoduser=None, sysseq=None, systag=None):  # noqa: E501
        """JobReportContacts - a model defined in Swagger"""  # noqa: E501
        self._idrec = None
        self._idrecjobcontact = None
        self._idrecjobcontacttk = None
        self._idrecparent = None
        self._idwell = None
        self._job_report = None
        self._pos = None
        self._syscarryfwdp = None
        self._syscreatedate = None
        self._syscreateuser = None
        self._syslockchildren = None
        self._syslockchildrenui = None
        self._syslockdate = None
        self._syslockme = None
        self._syslockmeui = None
        self._sysmoddate = None
        self._sysmoduser = None
        self._sysseq = None
        self._systag = None
        self.discriminator = None
        if idrec is not None:
            self.idrec = idrec
        if idrecjobcontact is not None:
            self.idrecjobcontact = idrecjobcontact
        if idrecjobcontacttk is not None:
            self.idrecjobcontacttk = idrecjobcontacttk
        if idrecparent is not None:
            self.idrecparent = idrecparent
        if idwell is not None:
            self.idwell = idwell
        if job_report is not None:
            self.job_report = job_report
        if pos is not None:
            self.pos = pos
        if syscarryfwdp is not None:
            self.syscarryfwdp = syscarryfwdp
        if syscreatedate is not None:
            self.syscreatedate = syscreatedate
        if syscreateuser is not None:
            self.syscreateuser = syscreateuser
        if syslockchildren is not None:
            self.syslockchildren = syslockchildren
        if syslockchildrenui is not None:
            self.syslockchildrenui = syslockchildrenui
        if syslockdate is not None:
            self.syslockdate = syslockdate
        if syslockme is not None:
            self.syslockme = syslockme
        if syslockmeui is not None:
            self.syslockmeui = syslockmeui
        if sysmoddate is not None:
            self.sysmoddate = sysmoddate
        if sysmoduser is not None:
            self.sysmoduser = sysmoduser
        if sysseq is not None:
            self.sysseq = sysseq
        if systag is not None:
            self.systag = systag

    @property
    def idrec(self):
        """Gets the idrec of this JobReportContacts.  # noqa: E501


        :return: The idrec of this JobReportContacts.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this JobReportContacts.


        :param idrec: The idrec of this JobReportContacts.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecjobcontact(self):
        """Gets the idrecjobcontact of this JobReportContacts.  # noqa: E501


        :return: The idrecjobcontact of this JobReportContacts.  # noqa: E501
        :rtype: str
        """
        return self._idrecjobcontact

    @idrecjobcontact.setter
    def idrecjobcontact(self, idrecjobcontact):
        """Sets the idrecjobcontact of this JobReportContacts.


        :param idrecjobcontact: The idrecjobcontact of this JobReportContacts.  # noqa: E501
        :type: str
        """

        self._idrecjobcontact = idrecjobcontact

    @property
    def idrecjobcontacttk(self):
        """Gets the idrecjobcontacttk of this JobReportContacts.  # noqa: E501


        :return: The idrecjobcontacttk of this JobReportContacts.  # noqa: E501
        :rtype: str
        """
        return self._idrecjobcontacttk

    @idrecjobcontacttk.setter
    def idrecjobcontacttk(self, idrecjobcontacttk):
        """Sets the idrecjobcontacttk of this JobReportContacts.


        :param idrecjobcontacttk: The idrecjobcontacttk of this JobReportContacts.  # noqa: E501
        :type: str
        """

        self._idrecjobcontacttk = idrecjobcontacttk

    @property
    def idrecparent(self):
        """Gets the idrecparent of this JobReportContacts.  # noqa: E501


        :return: The idrecparent of this JobReportContacts.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this JobReportContacts.


        :param idrecparent: The idrecparent of this JobReportContacts.  # noqa: E501
        :type: str
        """

        self._idrecparent = idrecparent

    @property
    def idwell(self):
        """Gets the idwell of this JobReportContacts.  # noqa: E501


        :return: The idwell of this JobReportContacts.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this JobReportContacts.


        :param idwell: The idwell of this JobReportContacts.  # noqa: E501
        :type: str
        """

        self._idwell = idwell

    @property
    def job_report(self):
        """Gets the job_report of this JobReportContacts.  # noqa: E501


        :return: The job_report of this JobReportContacts.  # noqa: E501
        :rtype: AnyOfJobReportContactsJobReport
        """
        return self._job_report

    @job_report.setter
    def job_report(self, job_report):
        """Sets the job_report of this JobReportContacts.


        :param job_report: The job_report of this JobReportContacts.  # noqa: E501
        :type: AnyOfJobReportContactsJobReport
        """

        self._job_report = job_report

    @property
    def pos(self):
        """Gets the pos of this JobReportContacts.  # noqa: E501


        :return: The pos of this JobReportContacts.  # noqa: E501
        :rtype: str
        """
        return self._pos

    @pos.setter
    def pos(self, pos):
        """Sets the pos of this JobReportContacts.


        :param pos: The pos of this JobReportContacts.  # noqa: E501
        :type: str
        """

        self._pos = pos

    @property
    def syscarryfwdp(self):
        """Gets the syscarryfwdp of this JobReportContacts.  # noqa: E501


        :return: The syscarryfwdp of this JobReportContacts.  # noqa: E501
        :rtype: int
        """
        return self._syscarryfwdp

    @syscarryfwdp.setter
    def syscarryfwdp(self, syscarryfwdp):
        """Sets the syscarryfwdp of this JobReportContacts.


        :param syscarryfwdp: The syscarryfwdp of this JobReportContacts.  # noqa: E501
        :type: int
        """

        self._syscarryfwdp = syscarryfwdp

    @property
    def syscreatedate(self):
        """Gets the syscreatedate of this JobReportContacts.  # noqa: E501


        :return: The syscreatedate of this JobReportContacts.  # noqa: E501
        :rtype: datetime
        """
        return self._syscreatedate

    @syscreatedate.setter
    def syscreatedate(self, syscreatedate):
        """Sets the syscreatedate of this JobReportContacts.


        :param syscreatedate: The syscreatedate of this JobReportContacts.  # noqa: E501
        :type: datetime
        """

        self._syscreatedate = syscreatedate

    @property
    def syscreateuser(self):
        """Gets the syscreateuser of this JobReportContacts.  # noqa: E501


        :return: The syscreateuser of this JobReportContacts.  # noqa: E501
        :rtype: str
        """
        return self._syscreateuser

    @syscreateuser.setter
    def syscreateuser(self, syscreateuser):
        """Sets the syscreateuser of this JobReportContacts.


        :param syscreateuser: The syscreateuser of this JobReportContacts.  # noqa: E501
        :type: str
        """

        self._syscreateuser = syscreateuser

    @property
    def syslockchildren(self):
        """Gets the syslockchildren of this JobReportContacts.  # noqa: E501


        :return: The syslockchildren of this JobReportContacts.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildren

    @syslockchildren.setter
    def syslockchildren(self, syslockchildren):
        """Sets the syslockchildren of this JobReportContacts.


        :param syslockchildren: The syslockchildren of this JobReportContacts.  # noqa: E501
        :type: int
        """

        self._syslockchildren = syslockchildren

    @property
    def syslockchildrenui(self):
        """Gets the syslockchildrenui of this JobReportContacts.  # noqa: E501


        :return: The syslockchildrenui of this JobReportContacts.  # noqa: E501
        :rtype: int
        """
        return self._syslockchildrenui

    @syslockchildrenui.setter
    def syslockchildrenui(self, syslockchildrenui):
        """Sets the syslockchildrenui of this JobReportContacts.


        :param syslockchildrenui: The syslockchildrenui of this JobReportContacts.  # noqa: E501
        :type: int
        """

        self._syslockchildrenui = syslockchildrenui

    @property
    def syslockdate(self):
        """Gets the syslockdate of this JobReportContacts.  # noqa: E501


        :return: The syslockdate of this JobReportContacts.  # noqa: E501
        :rtype: datetime
        """
        return self._syslockdate

    @syslockdate.setter
    def syslockdate(self, syslockdate):
        """Sets the syslockdate of this JobReportContacts.


        :param syslockdate: The syslockdate of this JobReportContacts.  # noqa: E501
        :type: datetime
        """

        self._syslockdate = syslockdate

    @property
    def syslockme(self):
        """Gets the syslockme of this JobReportContacts.  # noqa: E501


        :return: The syslockme of this JobReportContacts.  # noqa: E501
        :rtype: int
        """
        return self._syslockme

    @syslockme.setter
    def syslockme(self, syslockme):
        """Sets the syslockme of this JobReportContacts.


        :param syslockme: The syslockme of this JobReportContacts.  # noqa: E501
        :type: int
        """

        self._syslockme = syslockme

    @property
    def syslockmeui(self):
        """Gets the syslockmeui of this JobReportContacts.  # noqa: E501


        :return: The syslockmeui of this JobReportContacts.  # noqa: E501
        :rtype: int
        """
        return self._syslockmeui

    @syslockmeui.setter
    def syslockmeui(self, syslockmeui):
        """Sets the syslockmeui of this JobReportContacts.


        :param syslockmeui: The syslockmeui of this JobReportContacts.  # noqa: E501
        :type: int
        """

        self._syslockmeui = syslockmeui

    @property
    def sysmoddate(self):
        """Gets the sysmoddate of this JobReportContacts.  # noqa: E501


        :return: The sysmoddate of this JobReportContacts.  # noqa: E501
        :rtype: datetime
        """
        return self._sysmoddate

    @sysmoddate.setter
    def sysmoddate(self, sysmoddate):
        """Sets the sysmoddate of this JobReportContacts.


        :param sysmoddate: The sysmoddate of this JobReportContacts.  # noqa: E501
        :type: datetime
        """

        self._sysmoddate = sysmoddate

    @property
    def sysmoduser(self):
        """Gets the sysmoduser of this JobReportContacts.  # noqa: E501


        :return: The sysmoduser of this JobReportContacts.  # noqa: E501
        :rtype: str
        """
        return self._sysmoduser

    @sysmoduser.setter
    def sysmoduser(self, sysmoduser):
        """Sets the sysmoduser of this JobReportContacts.


        :param sysmoduser: The sysmoduser of this JobReportContacts.  # noqa: E501
        :type: str
        """

        self._sysmoduser = sysmoduser

    @property
    def sysseq(self):
        """Gets the sysseq of this JobReportContacts.  # noqa: E501


        :return: The sysseq of this JobReportContacts.  # noqa: E501
        :rtype: int
        """
        return self._sysseq

    @sysseq.setter
    def sysseq(self, sysseq):
        """Sets the sysseq of this JobReportContacts.


        :param sysseq: The sysseq of this JobReportContacts.  # noqa: E501
        :type: int
        """

        self._sysseq = sysseq

    @property
    def systag(self):
        """Gets the systag of this JobReportContacts.  # noqa: E501


        :return: The systag of this JobReportContacts.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this JobReportContacts.


        :param systag: The systag of this JobReportContacts.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobReportContacts, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobReportContacts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
