
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-23T02:57:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bae885e4eda7c0cea1cb3e852df73f728ce4714",
 "version": "0.5.dev2243"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
